### ISSUE TITLE
Opening delimiters break config.yml

### ISSUE THREAD

**Issue by erquhart** [netlify/netlify-cms#1051]
**- Do you want to request a *feature* or report a *bug*?**

*bug*

**- What is the current behavior?**

Opening delimiters (`---`) in config.yml cause problems, at least one of which being that new slugs end up populated with simply `---`, which the backend slug formatter crunches down to a blank string. This results an the following error (for searchability):

> Failed to persist entry: API_ERROR: refs/heads/cms/ is not a valid ref name.

**- If the current behavior is a bug, please provide the steps to reproduce.**

- Add opening delimiters `---` to config.yml
- Attempt to create a new entry

**- What is the expected behavior?**

Delimiters are valid yaml and should be allowed in config.yml without breaking the application.

**- Please mention your CMS, node.js, and operating system version.**

**- Please link or paste your `config.yml` below if applicable.**
Confirmed in 0.7.6 and 1.1.0

**Comment by tech4him1** [comment]
Weird, our YAML parser should support that by default: https://nodeca.github.io/js-yaml/.

**Comment by erquhart** [comment]
Yeah, I know. `entry.slug` somehow getting set to "---" was a real head scratcher.

**Comment by tech4him1** [comment]
@erquhart I can't reproduce in v1.4.0.

**Comment by kylekirkby** [comment]
Hi all,

Just been stuck with the same issue before I came across this issue on GH. If I removed the 
```
---
---
```
from the top of the config.yml file then new post slugs are formatted as expected otherwise they are merely three dashes `---`. If it weren't for this issue I may have not figured out the issue so soon. I've tested with the latest versions and it's definitely still an issue unless I'm missing something.

We need the dashes at the top of the file to dynamically add the required branch/repo/url for all of our static sites from the Jekyll site config.

Tested with:
[https://unpkg.com/netlify-cms@2.9.6/dist/netlify-cms.js](https://unpkg.com/netlify-cms@2.9.6/dist/netlify-cms.js)

Config file I'm working on:
https://github.com/kylekirkby/jumbo-jekyll-theme/blob/master/admin/config.yml

Kind regards,

Kyle

**Comment by hacknug** [comment]
Just encountered this issue when using spaces inside the slug moustaches.
- This works fine: `{{slug}}`
- This not: `{{ slug }}`

Guessing it's because of this line? 🤔 https://github.com/netlify/netlify-cms/blob/master/packages/netlify-cms-core/src/lib/stringTemplate.js#L22

**Comment by numoonchld** [comment]
I have the same issue in the latest netlify as of today. it occurs when I try to save a new post.

**Comment by erquhart** [comment]
Can someone open a new issue to track this?
