### ISSUE TITLE
Update folder-collection file name on title change  

### ISSUE THREAD

**Issue by TomPichaud** [netlify/netlify-cms#1195]
As the slug is generated from the title, it would be more accurate to update the file name when the title is changed, and so avoid non relevant name for the file.

No idea on how to do it thought...

**Comment by erquhart** [comment]
Not necessarily - we use the title to generate the slug because we need some way of creating a meaningful name, but changing the file name after publishing has big consequences, like breaking any existing links if a redirect isn't created.

The current thought is that this will be more or less fixed under #445, which will make the slug visible and editable, but afterward perhaps that behavior could be extended with configurable automatic redirect creation. For example, this would mean a new entry being created in the `redirects` file for sites hosted on Netlify.

**Comment by erezrokah** [comment]
Closing in favour of https://github.com/netlify/netlify-cms/issues/1576 due to the detailed discussion there.
