### ISSUE TITLE
Using multiple branches or multiple sites.

### ISSUE THREAD

**Issue by fessehaye** [netlify/netlify-cms#1266]
Hi! I am new to using netlify cms and was interested in using it for a side project. 

Is it possible to use the same cms and refer to multiple sites? For example, for posts and events I want to both city websites to refer to the same city .md files or back end data.

If I want to deploy two similar websites with the only differences being title changes and colors, is it best to make two branches within my repo or do I have to make two separate repos and how would that affect my config.yml?

This is my first time posting here so sorry if I missed something!

**Comment by adrw** [comment]
@erquhart related question, if I have a monorepo with many different websites, how can I configure a distinct CMS for each website in the monorepo? I ported sites from distinct repos but now the CMS for each website has broken though I updated them to point to the new monorepo. Any ideas?

**Comment by erquhart** [comment]
@adrw you'd have to provide details on _how_ they're broken. It's inherently valid to have an unlimited number of Netlify CMS instances because they don't know about one another, and they only target whatever directories and files you configure them to, so monorepo vs regular repo isn't a necessary distinction. To Netlify CMS it's just files.

**Comment by erquhart** [comment]
Ah, just saw #2250, will comment there.
