### ISSUE TITLE
Add a [VIEW LIVE POST] button to the UI

### ISSUE THREAD

**Issue by miguelmayo** [netlify/netlify-cms#1337]
**- Do you want to request a *feature* or report a *bug*?**
**_Feature_**
**- What is the current behavior?**
**_None_**
**- If the current behavior is a bug, please provide the steps to reproduce.**
**_N/A_**
**- What is the expected behavior?**
**_After a post or pages is published will be nice to see a button [VIEW LIVE POST] or similar next to [Published] button with a blank target._**

**- Please mention your versions where applicable.**

Netlify CMS version:
Browser version:

Node.JS version:
Operating System:

**- Please link or paste your `config.yml` below if applicable.**

**Comment by erquhart** [comment]
This is related to https://github.com/netlify/netlify-cms/issues/372, but specifically targets published posts. This would require:

* Design
* Deriving the published entry path (can be changed by generator, build scripts, deployment platform, etc)
* Determining whether the published entry has finished deploying (again, #372).

**Comment by mittalyashu** [comment]
@erquhart You was asking about the red dot. That concept can be used in this issue.

**Comment by marcojakob** [comment]
It would be really helpful for non-technical users to get information about what's going on during the build to know if the post is already live. Depending (it seems) on how busy the Netlify bots are, we're seeing shorte and also very long build times. This is very confusing for authors since they are never sure if something went wrong or if it just takes more time.

Would something like the `check for preview` be possible for the live version - a `check build status`?

**Comment by erquhart** [comment]
This actually should have been closed when #372 was closed - #2028 added a View Live button for published content: https://www.netlifycms.org/docs/deploy-preview-links/#preview-links-for-published-content

@marcojakob we should get a new issue open for that, and determine how best to do that using the backend (deploy preview links uses GitHub status checks).

**Comment by marcojakob** [comment]
Thanks @erquhart. I've opened #2324.
