### ISSUE TITLE
Feature Request: Media committed with Post / Collection Item

### ISSUE THREAD

**Issue by ro-savage** [netlify/netlify-cms#1344]
When running in `publish_mode: editorial_workflow` the current setup is to create a PR for the post / collection item but upload media directly to master ( or the `branch` specified in `backend`)

This means that images are automatically committed, while the collection item needs approval.

We would like to see, by default, when an image is uploaded to the media gallery it goes to the same PR as the collection item to be posted. 

This way both the collection item and any related media are contained in a single PR and can be reviewed and approved.

**Comment by haileypate** [comment]
Completely agree! I had not noticed this yet, but I'm days away from a use case where it would have come up. 

One of the things I hate about CMS media galleries I've used in the past is the clutter and thumbnail duplication that happens when unused/abandoned images sit in the filepicker window!

**Comment by ro-savage** [comment]
I created a very naive implementation for github.

Not useful to merge in here but might be useful for anyone who needs a quick implementation 

https://github.com/Encrypt-S/netlify-cms/commit/a86b5e87655dfcb60b3ae743219a614dca034157

https://www.npmjs.com/package/@encrypt-s/netlify-cms

**Comment by rdebeasi** [comment]
Awesome - thanks for submitting this!

In our use case, we'd like to open editing to the general public and have configured our site so that only admins can merge to master. Currently, users logged into Netlify CMS can edit content but cannot upload images because they are not allowed to commit directly to master.

**Comment by tech4him1** [comment]
> Currently, users logged into Netlify CMS can edit content but cannot upload images because they are not allowed to commit directly to master.

@rdebeasi That's a very good point, we'll definitely need to consider.

cc/ @Benaiah

**Comment by erquhart** [comment]
Not sure how that's possible, aren't write permissions required for successful login?

**Comment by erquhart** [comment]
Ah, protected branch, so the user does have write permissions, nevermind.

The closest solution is to use an [external media library](https://github.com/netlify/netlify-cms/pull/1602), a feature I expect to be merged in the near future. The first integration is Uploadcare and they have a great [free tier](https://uploadcare.com/pricing/).

**Comment by tech4him1** [comment]
@erquhart I think this is still worth discussing -- would you mind giving the reasons you decided to commit to master instead of the PR when you first worked on the media library?

**Comment by erquhart** [comment]
The reason media commits to master is because we wanted assets to be reusable between entries rather than being tied to them. If you had an oft used image you had to have access to it somewhere physically so you could upload it again every time you needed it in an entry. What we now see is that there's a need for both approaches.
