### ISSUE TITLE
NetlifyCMS 1.8.0+ with Gatsby Produces Warning

### ISSUE THREAD

**Issue by thekevinbrown** [netlify/netlify-cms#1389]
**- Do you want to request a *feature* or report a *bug*?**

Bug

**- What is the current behavior?**

Running `gatsby build` produces:

```
warning  in ./~/netlify-cms/dist/cms.js

Critical dependencies:
49:378-385 This seems to be a pre-built javascript file. Though this is possible, it's not recommended. Try to require the original source to get better results.
```

**- If the current behavior is a bug, please provide the steps to reproduce.**

1. Install `gatsby@1.9.261`, `gatsby-plugin-netlify-cms@2.0.1` and `netlify-cms@1.8.0`
1. Run `gatsby build`

**- What is the expected behavior?**

The site should be built without a warning

**- Please mention your versions where applicable.**
Netlify CMS version: ^1.8.0
Browser version: N/A
Node.JS version: latest
Operating System: OS X

**- Referenced Issue**

This issue was originally reported here: https://github.com/gatsbyjs/gatsby/issues/5485

**Comment by tech4him1** [comment]
@erquhart @KyleAMathews What is Gatsby wanting here? Does it want code that is transpiled but unbundled, or something else?

**Comment by willisplummer** [comment]
I've been running into this too

**Comment by esphen** [comment]
@tech4him1 I believe this is because Webpack wants ESM files, not a bundled UMD-file so it can do import analysis and tree shaking. 

It is pretty common to [build an unbundled project][babel] using babel then use [the `module` key][module] in `package.json` so that webpack uses the unbundled files as its entrypoint for the library.

[babel]: https://github.com/esphen/fetch-hoc/blob/master/package.json#L18
[module]: https://github.com/esphen/fetch-hoc/blob/master/package.json#L6

**Comment by grdp** [comment]
I just have updated the dependencies in a gatsby project and I'm running into the same WARNING with `netlify-cms`. Another weird thing is creating a folder `Users/username/…/gatsby-starter/public/` in the project root folder. As something was wrong the node path…
Does anyone encounter that also?

**Comment by grdp** [comment]
problem solved with `gatsby-remark-relative-images`

**Comment by tech4him1** [comment]
@esphen That's something we've been trying to figure out. The problem is that we currently have other assets like SVG and CSS that require a WebPack loader to split out. If there is a way to do that, I'd be glad to implement.

**Comment by tech4him1** [comment]
@heyalbert I believe we just need a way to address my comment above: https://github.com/netlify/netlify-cms/issues/1389#issuecomment-394730850.

**Comment by ericmasiello** [comment]
@tech4him1 @grdp can you elaborate on how to apply this fix?

**Comment by richtera** [comment]
The easiest I found to fix this is to use a pre-build using webpack that puts a fully built cms into static/admin and remove the plugin from gatsby. Is anyone interested in that solution? I made some changes in a PR in gatsby to partially fix the plugin for gatsby v2 but it turns out to be a lot harder when using a production compile of gatsby.

**Comment by githubr** [comment]
I am having exactly the same issue.

**Comment by githubr** [comment]
care to elaborate why you gave me thumb down @esphen? I mean, be clear on what I have done wrong so I will not do the same mistake in the future.

**Comment by esphen** [comment]
@githubr Sure. It's [pointless noise][noise] for the maintainers. Use the reaction feature to +1 the issue instead. 

[noise]: https://twitter.com/notbrent/status/1009884549587730432

**Comment by githubr** [comment]
@esphen thanks. I have deleted my post and +1 the OP. I will delete this one too.

**Comment by erezrokah** [comment]
Doesn't seem to happen in latest version of Gatsby and the cms plugin. Please re-open if needed.
