### ISSUE TITLE
Implicit grant type for Bitbucket

### ISSUE THREAD

**Issue by blopker** [netlify/netlify-cms#1547]
Hello! Now that Netlify supports Bitbucket, I'm wondering if it also supports the implicit oauth flow for Bitbucket?

According to Bitbucket the implicit flow is supported by them: https://confluence.atlassian.com/bitbucket/oauth-on-bitbucket-cloud-238027431.html 

It would be great to use Netlify CMS and Bitbucket without a server like the GitLab support.

Thanks for the great project!

**Comment by tech4him1** [comment]
The reason implicit authentication is not supported for BitBucket yet is because BitBucket requires that the user re-authenticates every hour. When using a server-side flow it provides a "refresh" feature so that the update can occur in the background. When using the implicit flow, however, the user would have to be asked to re-authenticate using some sort of popup. I had worked on this before in PR #560, but there are still issues to deal with so that users do not lose what they are working on.

**Comment by satyapramodh** [comment]
does implicit grant allow refresh tokens?
https://confluence.atlassian.com/bitbucket/oauth-on-bitbucket-cloud-238027431.html#OAuthonBitbucketCloud-Refreshtokens

**Comment by erquhart** [comment]
This should have been closed with https://github.com/netlify/netlify-cms/pull/2247.

@satyapramodh refresh tokens aren't supported for implicit grant, check the "Refresh Tokens" section: https://developer.atlassian.com/cloud/bitbucket/oauth-2/
