### ISSUE TITLE
Markdown works in Content Editor, displays un-parsed on my site

### ISSUE THREAD

**Issue by edadams** [netlify/netlify-cms#1596]
**- Do you want to request a *feature* or report a *bug*?**
Suspected bug.

**- What is the current behavior?**
I can type Markdown in the Content Editor but it is not being parsed on my compiled site. The unparsed Markdown is being outputted on my site instead. 

**- If the current behavior is a bug, please provide the steps to reproduce.**
In my Netlify CMS `config.yml` file, I've set `name: 'body', widget: 'markdown'` as per the docs.

**- What is the expected behavior?**
The Markdown should be parsed, bold, italics, etc.

**- Please mention your versions where applicable.**

Netlify CMS version: 1.9.2
Browser version: Chrome 67

Node.JS version: n/a
Operating System: n/a

**- Please link or paste your `config.yml` below if applicable.**

Config file is very long so [it can be found in full here (lines 28-30).](https://github.com/edadams/netlify-hugo-test/blob/master/site/static/admin/config.yml) Relevant section included below:

```yml
          - {label: "Text Area", name: "textbox", widget: "object", fields: [
              {label: "Title", name: "title", widget: string},
              {label: "Body", name: "body", widget: markdown}]} 
```

[This is the partial.](https://github.com/edadams/netlify-hugo-test/blob/master/site/layouts/partials/text-box.html) The title, which is a simple string, is outputted correctly.

[This is my test site on Netlify.](https://dreamy-stonebraker-53b9a4.netlify.com/) As you can see about half way down the page after it loads, the Markdown code displays unparsed. [This is my repo.](https://github.com/edadams/netlify-hugo-test/)

I've read in the [Netlify CMS  docs for the Markdown widget](https://www.netlifycms.org/docs/widgets/#markdown) that the field with Markdown must be called `body`, which mine is. 

I'm very new to Netlify CMS so I'm probably getting something wrong... Thank you! 👍

**Comment by tech4him1** [comment]
There are a few things here that need to be clarified, but thank you so much for providing all the links -- it makes it *way* easier to debug!

On the CMS side, `body` is only special if it is a top-level widget in the markdown file (i.e. not nested under another object like `textbox`). If it is top-level, it gets put into the body of the markdown file, not the frontmatter. Otherwise, `body` doesn't mean anything. There is no difference in markdown parsing that occurs either way, simply a location difference.

On the Hugo side of it, anything that is in the markdown file body get's parsed to HTML and put into the `.Content` [page variable](https://gohugo.io/variables/page/#page-variables). Frontmatter keys (like your `textbox.body`, do not get parsed at all unless you specifically do it yourself (i.e. `{{ .textbox.body | markdownify }}`).

As always, if you think we could change the wording in the docs to be more clear, please submit a PR!

**Comment by edadams** [comment]
>All I mean by top-level is that it is a field in the CMS config is directly on the file or folder, not nested under a `list `or `object `widget.

This has cleared it up for me. When you said "top-level" you mean it's... at the highest level of the config file. I'm not sure why this wasn't clicking for me before but it is now. 

I'll get started on trying to write that PR then! Thanks one last time. Closing this issue as my issue is properly resolved now.
