### ISSUE TITLE
Starter Sites/Examples

### ISSUE THREAD

**Issue by hhsnopek** [netlify/netlify-cms#16]
see [TODO.md#starter-sites](https://github.com/netlify/netlify-cms/blob/master/TODO.md#starter-sites)

We should at first have starter sites for:
- [x] Jekyll
- [ ] Middleman
- [ ] Roots
- [ ] Hugo

Later there are more to come and themes etc, would be great. But these four seems like the most important to start with.

**Comment by cedricdelpoux** [comment]
I saw you are interested into `Phenomic ` : https://www.netlify.com/blog/2016/04/19/a-step-by-step-guide-phenomic-on-netlify/

I use `netlify-cms` with `Phenomic` so I think it could be great to have starter site with it

**Comment by bdougie** [comment]
I created [this](https://choose.netlify.com) site to show off sites, at the moment I only have [victor hugo](https://github.com/netlify/victor-hugo) examples

**Comment by atelierbram** [comment]
I would like to see an example of a workflow with Grunt (and Hugo) ISO Gulp. Unsure how to convert the `gulp.task('cms'), () =>` into a Gulp task, ... (my javaScript skills are lacking). Can someone show in a code snippet how this might work?

**Comment by tortilaman** [comment]
I can possibly create a spike example.

**Comment by tech4him1** [comment]
Let's do Gatsby as well, we've been getting a lot of questions on it.

**Comment by erquhart** [comment]
We need to start looking at how best to feature these starters. It might be something for a separate issue, but throwing it out there for now.

**Comment by AustinGreen** [comment]
@erquhart let me know how I can help w/ this. I was looking for a spot to submit my gatsby starter template https://github.com/AustinGreen/gatsby-starter-netlify-cms/

**Comment by erquhart** [comment]
We were discussing this in [Spectrum](https://spectrum.chat/netlify-cms) - I'm leaning towards putting them right in the quick start, as a brand new project is what the majority of folks will be looking to do, as opposed to migrating an existing one.

cc/ @verythorough

**Comment by AustinGreen** [comment]
Agreed. The natural fit seems to be under the App File Structure heading in the quick start section

**Comment by verythorough** [comment]
I'd prefer to put the starters in Test Drive, and then link to them from the Quick Start. The Quick Start is really more about adding the CMS to an existing site, and adding a bunch of pre-made kits (with the CMS already fully implemented) will confuse that.

I see the Test Drive doc taking a slightly different structure, roughly:
1. Demo the UI - poke around cms-demo.netlify.com
2. Deploy a sample - using the one-click hugo example
3. Try a starter kit with your favorite generator - feature other starter kits here
4. Add to your own site - move on to the Quick Start

We might even consider combining 2 & 3, and make the hugo example just one of several. The biggest difficulty with handling all of the starter kits is the final setup instructions that may be necessary, like inviting users or going to site.com/admin. Eventually, I'd like to be able to configure these instructions to display in the UI at the end of a Deploy to Netlify flow, but until then, I suppose we can just refer people to the readmes for each starter.

I also wonder if the doc titles should be tweaked to make the "start with a kit" vs "add to your site" distinction clearer.

**Comment by biilmann** [comment]
Hmm, that seems a little confusing to me in the sense that when I go to the doc site, I would expect the Quick Start to show me the fastest way to get started, and I think that will always be starting from a starter template.

Integrating into an existing site is a much more involved process imo...

**Comment by biilmann** [comment]
Sorry - should be clear - linking to them from the quick start is good, but it should be the main way to encourage people to get started quickly, imo...

**Comment by verythorough** [comment]
Yeah, so maybe a title change would help with that.

In terms of starter kits being the primary way to get started, I don't think that's necessarily the case. It's certainly true for monolithic CMSs, because the CMS _is_ the site. You don't "add" WordPress to a site—you make a WordPress or Drupal site. But when the CMS is just one piece of the whole puzzle, "adding" it to existing parts becomes a very common use case, especially for people already using static site generators. (But this is a separate conversation...)

**Comment by tech4him1** [comment]
I'm wondering a little bit about the actual naming of "Test Drive" vs "Quick Start" here... I don't have any specific thoughts on it at the moment, but I think that that naming needs to be carefully considered here, with what goes where.

**Comment by biilmann** [comment]
I still think we'll find that the majority of people will end up starting new CMS projects with a starter template including the CMS, rather than starting without and adding it in later if all goes well (just like people are often starting their gatsby, hugo, react, hexo, jekyll, etc, projects with some boilerplate or starter).

If we delegate the starter templates from "Test Drive" sounds like the only use for the starter templates is to test the CMS, while we should end up having them be great starting points for new projects...

**Comment by verythorough** [comment]
Yeah, I think the titles are the main issue here, and the validity of separating "start from a kit" from "add to your site" content still stands.

For the titles, I lean towards changing both to something new, rather than, for example, renaming the Test Drive doc to Quick Start because it's a quicker start. I don't have any title suggestions atm, though, because I have a headache and thinking of titles is literally making my brain hurt. 😝

**Comment by erquhart** [comment]
Agreed, maybe just "Start with a Template" and "Start with an Existing Site".

**Comment by erquhart** [comment]
We need to refresh this with an updated list of static site generators that we'd like to see templates for. Some were created after this issue was opened, but are now far out of date.

**Comment by tech4him1** [comment]
Looking at www.staticgen.com, the top (by stars) site generators are:
- [ ] Jekyll
- [x] Hugo
- [ ] Hexo
- [ ] ~~GitBook~~ *Most likely irrelevant.*
- [x] Gatsby

I do still see a fairly high amount of support requests from Middleman users, so that would probably be a good one as well.

- [ ] Middleman

**Comment by erquhart** [comment]
@tech4him1 agreed on that list. I'd like to see a template that covers more use cases, maybe just an expansion/modernization on Kaldi, implemented across each of these, with identical output.

@verythorough just now circling back on the docs section naming - the mutual exclusivity between "Start with a Template" and "Add to Your Site" may not be all that apparent. It kind of looks like the former is step 1, and the latter step 2. Using "Start with/from" for each makes it clear that they're separate paths.

Maybe I'm the only that thinks this. Thoughts?

**Comment by tomrutgers** [comment]
Middleman starter:
https://github.com/tomrutgers/middleman-starter-netlify-cms
https://middleman-netlify-cms.netlify.com/

It needs some work on custom previews still, could use help with that.

**Comment by erquhart** [comment]
@tomrutgers nice!!!

We can definitely help on the previews. Can you add a footer along the lines of the one in the Hugo Kaldi? https://one-click-hugo-cms.netlify.com/

**Comment by tomrutgers** [comment]
Sure, no problem! Suggestions are always welcome.

**Comment by tomrutgers** [comment]
![footer](https://user-images.githubusercontent.com/6247534/44870400-6f74e500-ac90-11e8-8fb8-402c34f334c3.jpg)

**Comment by erquhart** [comment]
Opened a PR with the preview templates.

**Comment by erezrokah** [comment]
Closing this as stale/resolved as we have starters for:
- Hugo
- Gatsby
- Middleman
- Preact
- Next.js
- Eleventy
- Nuxt.js

We can open specific issues for other missing frameworks
