### ISSUE TITLE
Relationship widget

### ISSUE THREAD

**Issue by cassiozen** [netlify/netlify-cms#160]
# Relation widget:

## What is it:
A relationship wizard that let the user select one entry from another collection. For example: Select an Author for a post.

## How would it work:
Behind the scenes, it would use a search mechanism. It would be configurable somewhat like this (just a rough idea, not an actual implementation example)

`{label: "Author", name: "author", widget: "relation", collection: "authors", seachFields: ["first_name", ["last_name"]], display:["title"]}`

# What we need to figure out:
1. A way for a control widget to hook into search
2. A way for a control widget to set something else than just value (since the `value` will end up just being the “foreign key” while the preview widget will need access to the full relation object(s))
3. ...

**Comment by okonet** [comment]
Please consider following use cases when designig and implementing it:

## Author avatar in the entries list item

Right now we have an `author` in the front matter which comes as `String` in the format of `FirstName LastName`. It would really great to be able to display author of the post in the list of entries using avatar and being able to format the output as `Andre O.` for example.

## Change the author on the entry page

When editing a post it would be great to be able to pick an author from the autocomplete dropdown component instead of typing it.

## Categories

Manage categories as a separate collection and when assign a post to multiple categories with autocomplete widget on the edit entry page.

**Comment by biilmann** [comment]
Another use case we're seeing right now is managing a list of curated posts. For example selecting 6 curated posts that will appear on the front-page.

Eventually I think these different use cases will require several different relation widgets, rather than a one-size fits all. So I think the core thing we need to get right is the abstraction layers when building control and preview widgets to make sure all of these variations are easy to build (and make it easy to even tailor custom made relations widgets for specific projects)
