### ISSUE TITLE
Navigating to <Siteroot>/admin/ page leads to a system error popup

### ISSUE THREAD

**Issue by tonyrzhang** [netlify/netlify-cms#1626]
**Describe the bug**
So I just setup netlify-cms on my site and I saw that when I tried to navigate to <Siteroot>/admin/ I get an error popup below.
<img width="292" alt="screen shot 2018-08-17 at 9 33 05 am" src="https://user-images.githubusercontent.com/8292111/44277786-9fd47200-a200-11e8-9d52-b7b1eecc476e.png">

After clicking Ok, the admin page loads like normal and I'm able to interact with my collections, but I was just wondering what was causing this, since it's pretty alarming to our other users that modify the CMS content.

Thanks!

**Applicable Versions:**

 - Netlify CMS version: 1.7.0
 - Git provider: Github
 - OS: Mac OSX 10.13.2
 - Browser version Chrome Version 67.0.3396.99

**Comment by tech4him1** [comment]
This error message was added in https://github.com/netlify/netlify-cms/pull/550 to notify the user when caching cannot work due to the `localStorage` being full.

You could try clearing the `localStorage`/cookies for your site if you wanted to.

@erquhart @Benaiah I'm not sure why this is really necessary. Does it help to create a popup for users, or should we just handle silently?

**Comment by erquhart** [comment]
Shouldn't be a pop up, not sure why that's the case.

**Comment by tech4him1** [comment]
@erquhart Great! It was part of the initial PR which you reviewed, so I figured you might have an idea :wink::smiley:. We should be able to rework the `netlify-cms-lib-util/src/localForage.js` file to remove that `alert`. @tonyrzhang Feel free to create a PR if you're up for that.
