### ISSUE TITLE
Allow absolute paths in `public_folder`

### ISSUE THREAD

**Issue by erquhart** [netlify/netlify-cms#1668]
Migrated from #1257 for discussion.

**Comment by ahoward** [comment]
cool.  fwiw i am still blocked and would love to see this merged.  let me know if/when i can help.

**Comment by mryanb** [comment]
I'm stuck on this too. Our docs are hosted on a sub folder `docs.example.com/developer` File uploads should be a relative path to /developer. We can include `/developer` the public_folder setting but then paths are broken for anyone using locally which isn't on a sub folder.

**Comment by jballe** [comment]
Agree on this one, we would like to have a staging site with Netlify on GitLab pages while the final public site will be on its own domain.

My take so far is that I have replaced ``ImagePreview`` with my own implementation that changes the url. This works for preview but I would like to also change the url for the image selector control itself and for images in markdown. A general public absolute url prefix (and suffix), pattern or formatting function would be really helpful.

The code I add to my ``index.html`` if anyone can use is below. I ended up creating urls directly to the repo so that I don't have to wait for having the image published to the GitLab pages

```javascript
    const CustomImagePreview = createClass({
      render: function() {

        var value = this.props.value;
        var getAsset = this.props.getAsset;
        var field = this.props.field;
        var prefix = 'https://gitlab.com/<mygroup>/<myreponame>/raw/master/src/website/static';
        var suffix = '?inline=false';

        var uri = getAsset(value).public_path;
        if(prefix && uri && uri.substring && uri.substring(0, 1) === '/') {
          uri = prefix + uri + suffix;
        }

        var style = { maxWidth: '100%', height: 'auto' };
        return uri ? h('div', { style: style },
          h('img', { src: uri, role: 'presentation' })
        ) : null;
      }
    });

    CMS.registerWidget("image", "image", CustomImagePreview);
```

**Comment by jballe** [comment]
Maybe this will actually be solved by https://github.com/netlify/netlify-cms/issues/990

**Comment by erquhart** [comment]
That will help with image handling in the CMS, but image path output will still be prepended with `public_folder`, which will still be absolute.

**Comment by erquhart** [comment]
@erezrokah how is this impacted by the updates in our image handling?

**Comment by erezrokah** [comment]
I'm not sure I understand the use case for absolute paths in `public_folder`. If the use case was just to fix image previews in the CMS, due to recent changes the CMS loads images only using the API and not from the published site.

The only place the `public_folder` is used is when populating widgets data to be later used by site generators to locate the image in the repository.

Regardless, I've tested setting an absolute URL as a `public_folder` and it works.
