### ISSUE TITLE
TypeError: e.indexOf is not a function

### ISSUE THREAD

**Issue by fleaz** [netlify/netlify-cms#1689]
**Describe the bug**

Hi everyone,
I followed the QuickStart guide to add NetlifyCMS to my Hugo Blog (Repo is https://github.com/f-breidenstein/blog.felixbreidenstein.de). But after logging in and visiting `/admin` I see the interface for half a second and then appears a grey fullscreen error message telling me `TypeError: e.indexOf is not a function`.
Let me know if you need any more information.

Best regards,
Felix

**To Reproduce**
1. Follow Quickstart guide
2. Go to blog and use Identify to login
3. Go to '/admin'

**Expected behavior**
I expected to see the netlify-cms interface

**Screenshots**
![netlify-error](https://user-images.githubusercontent.com/2489598/44756174-a086d580-ab29-11e8-9bba-061924a1191a.png)

**Applicable Versions:**

 - Netlify CMS version: 2.0.11
 - Git provider: GitHub
 - OS: ArchLinux
 - Browser version FF Nightly 63, Chromium 68

**CMS configuration**

[Repo](https://github.com/f-breidenstein/blog.felixbreidenstein.de)

**Additional context**

**Comment by erquhart** [comment]
@tomrutgers it's a standard Hugo setup: https://gohugo.io/getting-started/directory-structure/

@f-breidenstein it's because your content structure doesn't match your configuration. Your config expects a string value at the `image` key, but you have at least one entry where the value is an object with a `feature` key.

We should be catching this though, I'll leave it open.

**Comment by f-breidenstein** [comment]
@erquhart Damnit. I did thought about this while writing the config.yml but then forgot to change it. Just fixed it and netlify-cms seams to work perfectly. Thanks!

And a big +1 for "Catching and providing helpful error messages" from me ;)
