### ISSUE TITLE
How to use different repo for local development?

### ISSUE THREAD

**Issue by eparizzi** [netlify/netlify-cms#1705]
Maybe I don't quite understand how netlify-cms works yet, but I understand that the CMS saves content by pushing commits to a git repository, right?

So I'm trying to setup a project using react-static and netlify-cms (using [this template](https://github.com/nozzle/react-static/tree/master/examples/netlifycms)). I deployed it to Netlify and I'm using Netlify Identity for authenticating to the /admin route.
This works fine, but I don't understand how to run and have a development "database" (I know this is a repo). So I don't need to push to the master repo while I'm developing and adding test data.

Is there a way to have different `config.yml` per environment? Or what's the suggested approach for this?

Thanks

**Comment by erquhart** [comment]
You can definitely have a different `config.yml` per environment, since it's a static file that the CMS looks for in it's own directory.

Netlify CMS will perform changes on your remote repository as you mentioned, even when running on a local development server, so you do need to pull changes down from your remote to have them reflected locally.

Personally, for local development I use the `test-repo` backend, which uses an in-memory object that is cleared with each refresh.

**Comment by schmkr** [comment]
> Personally, for local development I use the test-repo backend, which uses an in-memory object that is cleared with each refresh.

@erquhart can you explain how to set this up? I can't find any mention of this on https://www.netlifycms.org/docs/authentication-backends

**Comment by tomrutgers** [comment]
@schmkr
```
backend:
  name: 'test-repo'
```

**Comment by erquhart** [comment]
@schmkr if you need further assistance on this we can help you out in the [community chat](https://gitter.im/netlify/netlifycms).
