### ISSUE TITLE
Release Notes for 2.0 are... nowhere?

### ISSUE THREAD

**Issue by Quicksaver** [netlify/netlify-cms#1742]
Related to #1544 but not exactly the same. In addition to what was reported there, I could not find any release notes for version 2.0 anywhere. The [blog article](https://www.netlifycms.org/blog/2018/07/netlify-cms-2-0-launches-with-bitbucket-support-and-a-new-monorepo-architecture/) of course is only meant as a broad overview of it.

For example, apparently the cms.css file disappeared and all I can find out about it is #1724. That's a very big change to not be documented (apparently) anywhere.

**Comment by erquhart** [comment]
Yeah, part of 2.0 was the move to Lerna and automated changelogs. Those aren't really enough, it seems. The only reason it wasn't a red hot priority is because we didn't expect any changes to have been breaking - but it's definitely on the radar. Open to suggestions/help in getting a better changelog up for the project as a whole (to supplement the automatic ones in each package).

**Comment by tech4him1** [comment]
Of course, part of the problem is that there were no automated changelogs for v2.0 itself, only the versions after it.
