### ISSUE TITLE
Posts not fully loaded when using the back button

### ISSUE THREAD

**Issue by mryanb** [netlify/netlify-cms#1744]
**Describe the bug**
When you visit a post and press the back button, it doesn't load all of the posts that were previously there.

**To Reproduce**
1. Go to list of posts
2. Click on a post
3. Click the back button in the browser

**Expected behavior**
Expecting to see all the posts loaded

**Screenshots**

![2018-09-13_09-43-43](https://user-images.githubusercontent.com/3656391/45495918-e488f580-b739-11e8-9049-755e2d2d1d57.gif)

**Applicable Versions:**
 - Netlify CMS version: 2.1.1
 - Git provider: GitLab
 - OS: macOS
 - Browser version chrome 68.0.3440.106

**Comment by erquhart** [comment]
@Benaiah pagination thang?

**Comment by Benaiah** [comment]
@erquhart my guess is that this is most likely another instance of the react waypoint we use to load more posts on scroll not firing its visibility event despite the fact that it's visible. Perhaps we should add a "load more" button that manually triggers pagination so users can manually fire it when the waypoint fails.

What I think is happening:

- The "Doc" collection is being filtered somehow so that each page of API results is only loading a couple entries.
- The react waypoint frequently fails to fire its visibility event if you load a page that  doesn't have enough entries to trigger scrolling.
- This doesn't normally occur, since most collections load enough entries to trigger scrolling.

There's a variety of ways we can work around the bug, but the best way forward is likely to decouple API pagination from UI pagination, fix the instances where waypoint isn't indicating we need more entries, and add a manual fallback to load more entries just in case. The pagination already needs some UI work to indicate that it's loading more pages, so the manual trigger could probably be as simple as clicking the loading indicator.

**Comment by LoicMahieu** [comment]
I found a similar bug:

![kapture 2018-12-06 at 16 20 17](https://user-images.githubusercontent.com/900947/49593226-55bff980-f973-11e8-9295-9c5bd6cf965b.gif)

The problem here is that `react-waypoint` has already been mounted once, and this instance is reused across collections.
`react-waypoint` trigger the `onEnter`, when initially visible, only at `mount`.

**Comment by erquhart** [comment]
Sounds like we need a PR that repositions the waypoint so that it's remounted when a new collection is selected.

**Comment by sondrele** [comment]
@erquhart  I'm experiencing the same issue. 

I tried [passing a child to the Waypoint component](https://github.com/brigade/react-waypoint#children), and this change triggered the collection to re-fetch entries like the first time it's opened.
Could we utilize this to show e.g. a loading indicator in the Waypoint component? I'm not sure whether that's considered a hack or not, but it seams to be a feature of Waypoint component and it does seem to have the desired behavior. 

On a different, but somewhat related, note - are the collections supposed to be re-fetched when moving between them in the UI (like the gif above)? It makes the UI jitter a little bit.

**Comment by erquhart** [comment]
Not sure why it's completely refetching when you pass Waypoint a child, but we shouldn't need to do that. I'd expect to render a new Waypoint when we render a collection, whether the collection was previously navigated to or not. Superfluous fetching should be avoided at a higher level - and I don't see any in the gif above, it only shows fresh fetching (with the loading indicator) when a collection is first loaded. No spinner when navigating back to a collection that was previously loaded.

**Comment by sondrele** [comment]
> ..., it only shows fresh fetching (with the loading indicator) when a collection is first loaded. No spinner 
when navigating back to a collection that was previously loaded.

Maybe I'm mistaken, but this is what I see in the gif above:
1. Reload page
2. Select the `Pages` collection
3. Go back to the `Translations` collection
4. Observe that all previously fetched translations are visible for ~0.5s before they get re-fetched (and then we encounter the bug reported in this issue).

**Comment by barthc** [comment]
@LoicMahieu  we now have a PR to fix your related issue.

@erquhart I believe this issue is still related to unnecessary `loadEntries` calls,  which replaces the already loaded paginated id entries. Here is another gif that duplicates the issue. 

![anim](https://user-images.githubusercontent.com/8580864/50189624-5ae35800-0326-11e9-930e-2a574fd87a55.gif)

Notice after hitting the editor screen and back to the collection list page, the already loaded paginated entries are gone and you would need to scroll down for them to load again. PR  #1881 and #1964 should  fixed the issue.

**Comment by erquhart** [comment]
Merged both, will release soon.
