### ISSUE TITLE
Host on different domain than build. New Option: host_url

### ISSUE THREAD

**Issue by pungggi** [netlify/netlify-cms#1789]
**The Problem**
Image preview does not work when hosted on a domain per se.
Example
My Site:  https://super.com
Host of CMS: https://cms.com

Assume config.yml
`public_folder: media`

And image:  picture.jpg

The CMS will now point to _https://cms.com/media/picture.jpg_ for the preview...
![grafik](https://user-images.githubusercontent.com/5635709/46459708-f64e3d80-c7b9-11e8-90da-3cf4e9b6b7c9.png)

But in my case, here comes **the feature request**:

*Proposal config option : host_url*

Assume config.yml
```
public_folder: media
host_url: https://super.com 
```

Resulting in the preview pointing to:  _https://super.com/media/picture.jpg_ 
when accessing _https://cms.com_
because the images are hosted on https://super.com ...

**Comment by pungggi** [comment]
Dont know if this can be handle it here ? 
https://github.com/netlify/netlify-cms/blob/0596904e0b850d2ac9b15bd1a4055b392f36c819/packages/netlify-cms-core/src/valueObjects/AssetProxy.js#L7

Even if you dont accept that Request, some directions of how this could implemented in a nice way is much appreciated..

**Comment by tech4him1** [comment]
If the previews were fetched directly from the `media_folder` instead, would you need this change?

**Comment by pungggi** [comment]
You mean fetched from git? That should do the Trick!

Caleb <notifications@github.com> schrieb am Fr., 5. Okt. 2018, 17:06:

**Comment by tech4him1** [comment]
https://github.com/netlify/netlify-cms/issues/1668 would do what you originally suggested (allow absolute paths in the `public_folder`). However, there are downsides if you are simply using it for the reason outlined here, because that absolute path gets saved in the MD file.

If we just fetch the preview from Git instead, we don't have to mess with any of that stuff, since we are just changing the previews. We have been working on it in https://github.com/netlify/netlify-cms/issues/990. Both the GitLab and BitBucket backends are already fetching the thumbnails from Git, and we are hoping to get it working for GitHub soon.

**Comment by pungggi** [comment]
oh nice! Indeed I am using a private GitLab Repo.
I just turned id public to try this out, but still the previews dont show up I am using the latest cms version. Do I need to do something specific to enable this?

**Comment by pungggi** [comment]
so just to understand right, i do now see the preview in media assets but within the collection item not>
![grafik](https://user-images.githubusercontent.com/5635709/46554394-6525b680-c8e0-11e8-8568-07fc6e23ffe6.png)
