### ISSUE TITLE
Netlify CMS on self-hosted Bitbucket

### ISSUE THREAD

**Issue by KleoPetroff** [netlify/netlify-cms#1796]
Is there a way to use self-hosted Bitbucket as a backend? I saw in the documentation that there is a way to do it for Gitlab, but I didn't find anything for Bitbucket.

**Comment by talves** [comment]
At this time there is not support for a self-hosted Bitbucket backend using implicit grant like Gitlab. 

I am not sure if it is possible to setup an [external oath client like Github](https://www.netlifycms.org/docs/authentication-backends/#external-oauth-clients) at this time. I will leave this open for awhile to let the developer who did the backend for Bitbucket to chime in.

cc/ @Benaiah

**Comment by Benaiah** [comment]
The external OAuth client implementation doesn't work for BitBucket at the moment, since it needs to be able to handle token refreshing. In addition, I think there were some API differences between self-hosted BitBucket and the cloud version, but I don't think any of those differences broke core functionality.

In other words, once you have an external OAuth client that supports token refresh implemented, it shouldn't be difficult to adapt the BitBucket backend to use it (and _might_ not require any extra work at all), but that OAuth client hasn't been implemented yet to my knowledge.

**Comment by KleoPetroff** [comment]
Thanks for the info @talves and @Benaiah.

**Comment by santoshgistto** [comment]
any work around for selfhosted bitbucket ?

**Comment by santoshgistto** [comment]
is it possible to to add Basic Authorization header from `confg.yaml` file ?
`Authorization : Basic c2RhbjAwMDE6--`
