### ISSUE TITLE
Usability: resizing the panel split

### ISSUE THREAD

**Issue by rybit** [netlify/netlify-cms#183]
This is just some general feedback: 
  - the window split is not resizeable. I wanted to be able to look at the right panel in a larger panel (it was very squishy with our styles applied). 

**- Do you want to request a *feature* or report a *bug*?**
enhancement

**- What is the current behavior?**
- window split is not resizeable

**- If the current behavior is a bug, please provide the steps to reproduce.**
- just try and drag the window 

**- What is the expected behavior?**
- let me resize the splits

**- Please mention your node.js, and operating system version.**
```
Google Chrome	54.0.2840.98 (Official Build) (64-bit)
Revision	8ee402c67ff2f8f7c746e56d3530b4dcec0709ad-refs/branch-heads/2840@{#829}
OS	Mac OS X 
JavaScript	V8 5.4.500.41
```

**Comment by cassiozen** [comment]
We already have an opened issue for the ability to hide the preview. Should both exist?

@rafaelconde: I know you don't have all the time in the world for this project, but are there any suggestions for the show/hide preview interface?

**Comment by rafaelconde** [comment]
What's the effort to implement a resizing of the split?

A show/hide preview I think is a fair feature.

**Comment by cassiozen** [comment]
This one looks pretty easy to integrate. I would only take some time to see how it performs with complex nested dom trees...

https://github.com/tomkp/react-split-pane

Demo:
http://react-split-pane.surge.sh/percentage-vertical.html

**Comment by biilmann** [comment]
I think this would be really useful, also gives people an easy way to test the responsive styles on desktop vs mobile for a piece of content. We might think of having some presets rather than just relying on people dragging. I could imagine a small bar on top of the preview with options for full screen, half width, narrow view and no preview. This would also be more extensible in the future (ie, it could serve as a point where we could register different preview modes like "See post metadata as twitter card", etc)
