### ISSUE TITLE
Dragging relations inside list swap places

### ISSUE THREAD

**Issue by jclusso** [netlify/netlify-cms#1927]
**Describe the bug**
When you drag a relation field inside a list the data from the one being dragged will replace the data in the one that moves up into its place.

**To Reproduce**
1. Create some folder collection items
2. Create a file collection with a list of relations
3. Reorder an item

**Expected behavior**
The item moving up should not be replaced with the data from the item that was previously in that
 place

**Screenshots**
<img width="630" alt="screen shot 2018-11-30 at 12 24 02 pm" src="https://user-images.githubusercontent.com/622516/49304661-0a04e000-f49b-11e8-9db4-ec213a5c0c8e.png">
<img width="623" alt="screen shot 2018-11-30 at 12 24 12 pm" src="https://user-images.githubusercontent.com/622516/49304662-0a04e000-f49b-11e8-815b-e7541290deb3.png">

**Applicable Versions:**
 - Netlify CMS version: 2.2.1
 - Git provider: GitHub
 - OS: OS X
 - Browser version: Chrome Version 70.0.3538.77

**Comment by barthc** [comment]
@erquhart  dug a little deep about this issue and noticed a couple of things. First of all, this issue only happens on the initial load of editor page for an existing collection that has `relation` widget inside `list` widget. 
So on page load, the relation widget makes this [query](https://github.com/netlify/netlify-cms/blob/master/packages/netlify-cms-widget-relation/src/RelationControl.js#L79) but  the `componentDidUpdate` won't fire because widget component only update on `value` , ` classNameWrapper` or `hasActiveStyle` changes.  So when you reorder the widgets, the `onchange ` handler in the `list` widget reorder values , and then the `componentDidUpdate` (we have a value change) and then this [onchange](https://github.com/netlify/netlify-cms/blob/master/packages/netlify-cms-widget-relation/src/RelationControl.js#L97) handler  which is the culprit.

**Comment by erquhart** [comment]
Finally hitting this one in my notifications queue (oldest first) - thanks for getting a fix up @barthc, hitting the PR queue next.
