### ISSUE TITLE
Allow markdown code blocks in the editor

### ISSUE THREAD

**Issue by WebStackDev** [netlify/netlify-cms#209]
**- Do you want to request a *feature* or report a *bug*?**

- feature (possibly bug?)

**- What is the current behavior?**

- trying to include markdown code blocks (\`\`\`) in an editor markdown widget field "by hand" does not write them to the output .md file

**- If the current behavior is a bug, please provide the steps to reproduce.**

- not sure it's a bug or not implemented funtionality

**- What is the expected behavior?**

- the editor will write to the .md file (i.e. on github) WITHOUT escaping/removing the back ticks the following (preferably maintaining the "code language" i.e. the "js" in the example below, so it can be used by syntax highlighters):

\`\`\`js
// some sample code
const f = () => {
  console.log('foo');
}
\`\`\`

- more about this here: https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#code

**- Please mention your node.js, and operating system version.**

**Comment by tcbyrd** [comment]
This appears to be a bug. When I look at the PR it creates, the diff shows it's adding 4 spaces to the beginning of the code block:

```diff
+    ```js
+    function () {
+    }
+    ```
```

Which renders as:
```
    ```js
    function () {
    }
    ```
```

Removing the spaces at the beginning correctly renders as:

```js
function () {
}
```

I think it's because the [component](https://github.com/netlify/netlify-cms/blob/master/src/components/MarkupItReactRenderer/index.js#L9-L12) is reading the html and adding both `<pre>` and `<code>` blocks, but I'm not 💯 sure of the solution.

**Comment by erquhart** [comment]
Closing in favor of #246
