### ISSUE TITLE
Forking in the Editorial Workflow

### ISSUE THREAD

**Issue by erquhart** [netlify/netlify-cms#2096]
Netlify CMS backends currently only work if you have write access to a repository. If you don't have write access to a repository, contributing generally involves:

- creating a fork
- committing changes in a new branch
- opening a pull/merge request in the source repo

Git hosts support forking via API, so Netlify CMS should be able to facilitate editing content through forking and pull requests.

## Expected approach

The current editorial workflow functionality in the GitHub backend can be supplemented to utilize a fork. The following should occur when persisting a change:

1. Call the [create fork](https://developer.github.com/v3/repos/forks/#create-a-fork) endpoint, which will create a fork if it doesn't already exist and return info about the fork
2. Be ready to poll in case the fork is being created and git objects aren’t ready
3. Get the PR base branch SHA from the source repo
4. Create a new branch in the fork repo referencing the SHA from the source repo
5. Use this branch for standard editorial workflow procedure
6. Open PR against the source repo

## Activation Developer/User Experience

Forking can be implemented in such a way that it automatically works for the GitHub backend, making it zero effort for implementing developers.

For editors, forking should be used if the editor does not have write access to the repository being edited.

1. [Check for write access](https://developer.github.com/v3/repos/collaborators/#review-a-users-permission-level)
2. If the user has write access, use the standard editorial workflow
3. If the user does not have write access, notify them that a fork will be created if it does not already exist, and a PR will be opened from the fork.
4. If the user does not confirm that forking is okay to do, do nothing.
5. If the user confirms forking is acceptable, proceed with PR from fork.

**Comment by Benaiah** [comment]
Here's a writeup I've done investigating the forking process in the CMS, step by step:

<a id="orgcb19887"></a>

# Netlify CMS GitHub forking workflow


<a id="orgd3cdb53"></a>

## Authenticate as the GitHub user

When logging into the CMS, the user will use their own GitHub account. Ideally, we could then tell if the user has permissions to access the repository using the [`/repos/:owner/:repo/collaborators/:username/permission`](https://developer.github.com/v3/repos/collaborators/#review-a-users-permission-level) endpoint, and automatically offer to fork the repo if the user does not have write permissions to the repo. However, that endpoint is currently in a "preview period" and the GitHub documentation indicates it should not be relied upon in production. We have two alternatives to using this API endpoint:

1.  Use separate instances of the CMS, one which uses the forking workflow and does not allow publishing entry drafts, and one which uses a traditional Netlify CMS setup and allows entry drafts to be published.
2.  Require a list of specific GitHub accounts which can access the repo directly be provided in the repo or in the CMS configuration. The CMS will access the repo in the traditional manner for these specified maintainers (who will thus be able to publish entries), but accounts outside of the specified list will use the forking workflow.(*Q: Should maintainers also use the forking workflow for everything but publishing?*)


<a id="org4d229b0"></a>

## Check for a fork

Once the user agrees to fork the repository to edit, we need to find out if the user has an existing fork. This can be done one of three ways:

1.  Require that the user's fork be named the same as the original repository. This is *almost* always the case, but there are exceptions. Use that repo.
2.  Using the [`/repos/:owner/:repo`](https://developer.github.com/v3/repos/#get) endpoint, we can check the repo of the same name as the original repo. If that is not a fork of the original repo, request the list of all the user's repos with the [`/user/repos`](https://developer.github.com/v3/repos/#list-your-repositories) endpoint. Iterate through these, requesting the repo info on each, until we find a fork of the original repository. This is expensive in the worst case, but should be able to be cached almost indefinitely.
3.  The same approach as 2, but iterating through the list of forks of the original repo at the [`/repos/:owner/:repo/forks`](https://developer.github.com/v3/repos/forks/#list-forks) endpoint to find a fork by that user instead of iterating through the user's repos to find a repo which is a fork.


<a id="orgdf16ffc"></a>

## Create a fork if none exist

If no fork exists for the user, we can trigger its creation with the [`/repos/:owner/:repo/forks`](https://developer.github.com/v3/repos/forks/#create-a-fork) endpoint. Unfortunately, this endpoint is asynchronous, so we'll have to poll to determine when the repo has been created and is ready to edit. Once it is, we can complete the user's login process and begin pulling data from GitHub.


<a id="org521fe49"></a>

## Creating a new entry

When creating a new entry, we will create the branch and commits on the user's GitHub account. When a repository on GitHub is a fork, it is able to create new branches using a SHA reference to an object in the repo it was forked from.


<a id="orgb52ee3b"></a>

## Making an entry ready to review

To avoid spamming maintainers with PRs of unfinished posts, we might want to implement a staged system where draft posts only exist on the forked repo, and moving them to "Ready to Review" actually creates the PR on the original repo. The "Publish" button should also be changed to "Submit for review", unless the user is a maintainer of the original repo. Once the entry is submitted, we should create a PR on the source repo using the SHA of the branch in the fork.


<a id="org3e8f357"></a>

# Concerns


<a id="org7085e59"></a>

## Image display from `display_url`

We cannot depend on any new images being uploaded to the site specified by `display_url` until they have been published to the original repo and a build has completed. Additionally, our current approach of updating the master branch with images so that we can load them from the site will not work, since all new content will have to be contained in a single PR. The solution for this is to pull images through the API exclusively, which we already have code for (even though we don't use it everywhere in the UI). This won't necessarily be possible in all cases (consider build images that don't map 1:1 with source images, like multiple resized versions of a single image created at build time), but we should be able to cover the common ones.


<a id="org7104f25"></a>

## No deploy previews until the PR on the source repo is created

If we don't create PRs immediately when saving a draft, as suggested above, deploy previews will be unavailable until the entry is submitted for review (which, in this approach, would create the PR on the source repo).


<a id="orge06ccc2"></a>

## `git-gateway` as an alternative

As `git-gateway` does not currently have any role enforcement, we cannot authenticate non-maintainer accounts using it. We could limit their actions in the UI, but they would still have access to the JWT token that edits the original repo, with all the permissions that encompasses.

However, there are downsides to not using `git-gateway`. All editors must have GitHub accounts in order to use the forking workflow (it's fundamental to the approach), and a lack of an Identity login means we can't use Netlify features which require Identity. It might be possible to allow users to log in to both in order to authenticate with Identity without using `git-gateway` for API access, but that would be a messy user experience.

It would be possible to support OSS contributions in `git-gateway`, but it would entail adding a role system requiring gating and rewriting responses for all available API endpoints, which would be a significant time investment.

**Comment by erquhart** [comment]
More thoughts on UX/DX:

1. User loads CMS
2. After login, if GitHub + EW active and they don't have write access, notify that fork will be created if it doesn't exist, and that edits will happen in the fork.
3. Use localstorage to remember that a fork was fetched/created and just use it in the future.
4. If they decline forking, they can't log in and view the admin at all
5. If they accept, the CMS is running entirely from their fork at that point, not the original repo.
6. When running from a fork, it needs to use a special branch that is owned by the CMS, some kind of `CMS-BASE` branch or something. That branch should be updated with the latest from upstream branch (whichever branch is configured).
7. Editorial workflow branches should be able to work exactly as they do now.
8. If possible to uncheck "allow maintainers to edit branch" option if that's still possible, we should to avoid breaking EW PR's with unexpected edits from maintainers.
9. When an entry is saved, drafts should not create a PR, only waiting for review/ready to publish should.
10. When moving from draft to Ready for Review, a notification should be provided that this will open a PR in the upstream repository.
11. The user should be able to (optionally) provide the title and message for the PR. Not sure where this should happen. We can tack this on at the end of development.
