### ISSUE TITLE
Collections filter displays incomplete information

### ISSUE THREAD

**Issue by theKashey** [netlify/netlify-cms#2132]
**Describe the bug**
__netlify cms is backed by BitBucket__.

[Filtered folder collections](https://www.netlifycms.org/docs/collection-types/#filtered-folder-collections) are not displaying information they should.

- There is a main collection, with 200 entities inside. _Everything_ is visible inside.
- There are 10 filters to scope it a bit. _Something_ is visible inside.

From network tab it's visible that for the main tab Netlify is making lots of paginated requests to the backend, while in the categories - only 2.

**To Reproduce**
1. Create a collection with 100 items
2. Create 2 filters
3. Not all data would present under filters.

**Expected behavior**
1. All data should be visible.

**Applicable Versions:**
netlify-cms 2.5.1

**CMS configuration**
 https://mktomskiy.netlify.com/admin/config.yml

**Additional context**
Yes - keep in mind - BitBucket.

**Comment by erquhart** [comment]
Can you help with a minimal reproduction? Does it require 100 items or does it happen with less? Does it happen with just one filter?

**Comment by theKashey** [comment]
Good points. Let me try to reduce a scope.

**Comment by zdenekdrahos** [comment]
@erquhart: we have similar issue.

**Describe the bug**

No article is shown in filtered collection.

**To Reproduce**

1. [Folder](https://gitlab.com/sokolmorasice/web/tree/0f7c4854/source/%C4%8Dl%C3%A1nky/2019-2020) has 46 articles
2. [Collection filter](https://gitlab.com/sokolmorasice/web/blob/0f7c4854/source/admin/config.yml#L57) contains only articles from 1st page _(alphabetically ascending order)_
3. Reload page with collection in netlify-cms (`/#/collections/clanky-dorost`)
4. No article is visible, because pagination loads only two pages

**Expected behavior**

See filtered articles from all pages. They might not be on last two pages

**Screenshots**

![page: 3](https://user-images.githubusercontent.com/7994022/64029761-879e6f00-cb45-11e9-8c79-80c0ebffb6bf.png)
![page: 2](https://user-images.githubusercontent.com/7994022/64029762-879e6f00-cb45-11e9-97b3-196ada330ce3.png)

**Applicable Versions:**

 - Netlify CMS version: ^2.0.0
 - Git provider: Gitlab
 - Browser version: Chrome 76

**CMS configuration**

* https://gitlab.com/sokolmorasice/web/blob/0f7c4854/source/admin/config.yml#L57
* https://gitlab.com/sokolmorasice/web/tree/0f7c4854/source/%C4%8Dl%C3%A1nky/2019-2020

**Comment by erquhart** [comment]
Need to pull this down and test it out, will circle back.
