### ISSUE TITLE
Widget default value is not used if field is missing from frontmatter

### ISSUE THREAD

**Issue by alexandernanberg** [netlify/netlify-cms#2164]
**Describe the bug**

The default value is not used if a value non existent ie `undefined`. 

**To Reproduce**

I you have a field defined like this

```yml
name: 'published'
label: 'Published'
widget: 'boolean'
default: true
```

then a md file looking something like this

```md
---
title: 'Hello world'
---

My first post!
```

when editing that post the value of the `published` field will be false.

**Expected behavior**

I think it would make sense to use the default value of the field if a value/field is missing in the frontmatter. So in the case above the value would have been true since it was defined as the default value.

**Screenshots**
N/A

**Applicable Versions:**

 - Netlify CMS version: 2.6.1
 - Git provider: N/A
 - OS: N/A
 - Browser version: N/A
 - Node.JS version: N/A

**CMS configuration**
N/A

**Additional context**
N/A

**Comment by erquhart** [comment]
I wouldn't expect default values to apply to existing entries, only for new ones.

**Comment by alexandernanberg** [comment]
Hmm I would as long as the value is `undefined` 🤔  I think it could be very useful like in my scenario above, where you add a field after a lot of content already exists.

**Comment by erquhart** [comment]
What if you want the value to be undefined? Every time you edit the entry this field would auto populate an unwanted default value. The CMS doesn't know whether the field was added to the config after the fact or not. In the future when we have a config UI, that would present a great place to handle these kinds of migratory operations, because the CMS would be handling the addition of the new field and can provide the option to update existing entries.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by alexandernanberg** [comment]
Good point. What if it only auto populated when the field is required? But yeah, having a way to migrate the old content is probably the better option.

**Comment by erquhart** [comment]
Closing in favor of #1745.
