### ISSUE TITLE
Github backend should work with Netlify Large Media

### ISSUE THREAD

**Issue by abstracthat** [netlify/netlify-cms#2229]
We use `backend: github` and just finished switching to Netlify Large Media but I see the CMS is still uploading the files as binary and loading previews from github. Is there a technical limitation for this? I can help with a PR with some direction. @Benaiah thoughts?

**Comment by Benaiah** [comment]
@abstracthat unfortunately this won't be possible, since Netlify Large Media uses the Netlify Identity token to authenticate API requests, so you'd still have to log in to Netlify Identity _after_ logging into GitHub. Additionally, the current implementation assumes pretty widely that it's being used with the `git-gateway` backend, and that only one user login is required to authenticate the CMS.
