### ISSUE TITLE
Logging in requires lots of extraneous clicks with Netlify Identity

### ISSUE THREAD

**Issue by freshyill** [netlify/netlify-cms#2260]
**Describe the bug**

I'm not totally sure if this issue is with Netlify CMS or Netlify Identity. Please feel free to close this if this is the wrong place.

When I log in, I need to do several unnecessary clicks in order to get overlays to go away so I can click on the buttons.

**To Reproduce**
1. Go to site/admin
    * The "Login with Netlify Identity" button appears
    * An overlay will immediately cover it
1. Click the overlay
    * The overlay will go away, making the  "Login with Netlify Identity" clickable
1. Click "Login with Netlify Identity"
    * The Log in dialog will appear
1. Click "Continue with GitHub"
    * The "Login with Netlify Identity" button appears again
    * An overlay will immediately cover it
1. Click the overlay
    * The overlay will go away, making the  "Login with Netlify Identity" clickable
1. Click  "Login with Netlify Identity"
    * Success!

**Expected behavior**

1. "Login with Netlify Identity" should be immediately clickable
1. Clicking "Login with Netlify Identity" should bring up the Netlify identity widget iframe
1. Entering an email and password or clicking an identity provider should take you to the admin, not back to the "Login with Netlify Identity" button

**Screenshots**

The gif shows all the clicks to remove unnecessary overlays.

![in](https://user-images.githubusercontent.com/879292/55285088-49144680-5352-11e9-95ae-5adbabd5bc5b.gif)

**Applicable Versions:**

 I don't get as far as the actual admin, so I'm skipping this for now. I can add it if it's helpful.

**Additional context**

Some quick inspecting shows that th`#netlify-identity-widget` iframe has a positioning and z-index issue. It also `display: block !important` set.

**Comment by erquhart** [comment]
Would definitely take a PR for this (perhaps some or all of the fix needs to happen upstream in the `netlify/netlify-identity-widget` repo, not certain.

**Comment by groundedSAGE** [comment]
I have a similar issue. Overlays were showing up at one point but seem to have stopped. What happens is:

1. Click the Login with Netlify Identity
2. Login with email and password.
3. Modal says I have successfully logged in but remains up.
4. Manually close modal
5. Click on Login with Netlify Identity again
6. Success

**Comment by watershed** [comment]
I have similar thoughts. 

Specifically, the login overlay's fields are not available to the 1Password browser extension. One has to manually enter the username and copy the password and paste, rather than merely click the named resource found by 1Password.

**Comment by erquhart** [comment]
If you want this issue to be prioritized, add a thumbs up reaction to the issue, that's how we track community priorities.

**Comment by Rumyra** [comment]
This is actually a blocker.

When the first overlay comes up, I experience different behaviour to @freshyill in that I can not click it to remove it. I have to go into devtools, there is a modal there, but you can not see it, even when you remove the visuallyhidden class, you can not see it, you have to waver your mouse where the close button and try and close it. Only then can you click the Login with Netlify button.

Also if you are authored it dumps you in the CMS, which if you _are_ authed, why is that the user flow in the first place?

This is not a beginner issue or a pr, this is a bug and a blocker for users at that.

The only way I am able to use the CMS is because I am familiar with devtools - this really needs to be looked at as a priority.
