### ISSUE TITLE
Custom editor components doesn't work with grave accents 

### ISSUE THREAD

**Issue by mariana-martins** [netlify/netlify-cms#2266]
**Describe the bug**
Markdown to html isn't working if a custom editor component relies on ` char (grave accent).  Grave accents are considered code regardless of setting up custom editor components.

Use case: Trying to use Netlify CMS with gatsby-remark-embed-video, that relies on pattern `youtube: <ID>` to show youtube videos.

**To Reproduce**

- Create a editor component that used a pattern with ` char (grave accent)
```
// EXAMPLE
const editorComponentDefinition = {
  id: 'youtube',
  label: 'Youtube',
  fields: [{ name: 'id', label: 'Youtube Video ID', widget: 'string' }],
  pattern: /^`youtube: (\S+)`$/,
  fromBlock: match => {
    const id = match[1];
    return { id };
  },
  toBlock: obj => `\`youtube: ${obj.id}\``,
  toPreview: obj =>
    `<img src="http://img.youtube.com/vi/${
      obj.id
    }/maxresdefault.jpg" alt="Youtube Video"/>`
};
```
- Register new editor component on CMS object, using `registerEditorComponent` method
- Create a collection with a `body` field, type `markdown`
- Register a preview template for the new collection, using `widgetFor('body')` to show body field data
- On admin page, add a new item for the collection
- Add the new component on body field
- At this moment, preview is wrong, should it as a code
- If you change view mode to Markdown and back to Rich Text, it will lose its reference as a component

Example code: https://codesandbox.io/s/1ynr8825r3 - thanks Tony Alves (gitter: @talves)

**Expected behavior**
- Preview shows the correct preview output
- Changing between view mode preserves initial behavior

**Applicable Versions:**
 - Netlify CMS version: 2.9.0
 - Git provider: GitHub
 - OS: macOS Mojave
 - Browser version: Chrome Version 73.0.3683.86 (Official Build) (64-bit)
 - Node.JS version:

**CMS configuration**
Available at https://codesandbox.io/s/1ynr8825r3

**Additional context**
Available at https://codesandbox.io/s/1ynr8825r3

**Comment by erquhart** [comment]
We can't currently target markdown as a Shortcode pattern. So this means:

```
// works
{{ youtube 123 }}

// won't work
`youtube 123`
```

I'll illustrate why this is the case - here's the first couple of things the Markdown widget does with a markdown string:

1. Convert the raw markdown string to an object that represents the original markdown, an AST (Abstract Syntax Tree)
2. Check each paragraph node for a shortcode match using the registered editorComponent patterns

When we check for your editor component pattern, we're not checking it against the entire raw markdown string, mostly because this slows the CMS to a crawl for large documents. Instead, your pattern is being checked against each top level paragraph, but with the paragraph's markdown symbols removed. So "`youtube 123`"  is actually "youtube 123".

Again, most of this was set up in the name of performance - all of our shortcode/editorComponent handling needs to overhauled. But this is where it stands at the moment, you'll need to use symbols that are meaningless in Markdown for your patterns.

**Comment by mariana-martins** [comment]
Thank @erquhart for helping on this one! Hope #2268 is merged soon!
