### ISSUE TITLE
[Question] Netlify form and adding content

### ISSUE THREAD

**Issue by julienchazal** [netlify/netlify-cms#2341]
**Is your feature request related to a problem? Please describe.**
Is it possible to create content automatically after Netlify form submission ?

**Describe the solution you'd like**
I've implemented a Netlify form inside my Nuxt/Netlify-CMS project.
I've got a page with a list widget inside.
When a user submit the form, automatically it would add an item to the list widget with the values of the form fields

Thx :)

**Comment by julienchazal** [comment]
Anyone please ? @erquhart ?

**Comment by erquhart** [comment]
> I've got a page with a list widget inside.

Can you explain that a bit more? Do you have the Netlify CMS list widget running standalone on a page in your website?

**Comment by erquhart** [comment]
Oh just realizing you're describing what you want to do, not what you're currently doing. The short answer is that Netlify CMS mostly functions as a full on application at the moment. At some point in the future I'd like to see individual pieces functioning well outside of the CMS, or more specifically, the CMS being a React _component_ instead of a React _app_, so micro-instances can be embedded as you're describing. But at the moment, Netlify CMS won't help this use case.

**Comment by julienchazal** [comment]
ok thx
