### ISSUE TITLE
Bug: Merging PR in GitHub without deleting branch causes trouble

### ISSUE THREAD

**Issue by biilmann** [netlify/netlify-cms#251]
If a CMS generated PR gets merged through GitHub without deleting the CMS branch, the editorial workflow keeps the card, but any attempt at publishing it fails.

**Comment by Benaiah** [comment]
@biilmann looking at GitHub's API docs, it seems we can [check if a PR has been merged](https://developer.github.com/v3/pulls/#get-if-a-pull-request-has-been-merged).

The only issue is that `listUnpublishedEntries` checks and returns objects from the refs API, not the PR API. We'd need to get a PR number from the returned ref in order to filter the list.

**Comment by Benaiah** [comment]
@biilmann after further investigation, it looks like we can find the appropriate PRs with a URL like the following:

https://api.github.com/search/issues?q=repo:Benaiah/netlify-cms-test-repo%20type:pr%20state:open%20head:cms/2017-02-24-yada-yada-yada

As you can see, the "head" parameter is unfortunately not exclusive - it searches for PRs that have a *substring match* on the "head" parameter. To successfully filter, we'd need to either take the first result (fragile) or figure out a way to restrict the search to only exact matches of the "head" parameter.

Our other option is to get unpublished branches *from* the list of PRs, not the other way around - this would likewise use the search API.

Thoughts?
