### ISSUE TITLE
CMS Preview - Error message

### ISSUE THREAD

**Issue by maxerdenberger** [netlify/netlify-cms#2511]
**Describe the bug**
When viewing a current or new post in the edit mode. the right hand side preview doesn't appear. Type error: cannot read property 'fluid' of underfined.

**To Reproduce**

**Expected behavior**

**Screenshots**
[](url)

**Applicable Versions:**

 - Netlify CMS version: [e.g. 2.0.4]
 - Git provider: [e.g. GitHub, BitBucket]
 - OS: [e.g. Windows 7]
 - Browser version [e.g. chrome 22, safari 11]

 - Node.JS version:

**CMS configuration**

**Additional context**

**Comment by maxerdenberger** [comment]
<img width="1273" alt="Screenshot 2019-07-30 17 36 06" src="https://user-images.githubusercontent.com/51494570/62175015-e7102180-b2f0-11e9-9210-c65c3676da23.png">

**Comment by chrfritsch** [comment]
I had the same issue. Now I am using https://github.com/netlify-templates/gatsby-starter-netlify-cms/blob/master/src/components/PreviewCompatibleImage.js for displaying images and that works fine.

**Comment by erquhart** [comment]
Gotta fill out the issue template buddy. I will say that the term "fluid" isn't in the Netlify CMS codebase, so this is an issue with your custom preview template, I'd recommend focusing your debugging there.

**Comment by maxerdenberger** [comment]
ok buddy

**Comment by erquhart** [comment]
Hey @maxerdenberger - running back through my notifications and reread this, apologies for the harsh response. Noticed you joined GitHub just to open this issue and probably had no clue the template needed to be filled out.

Some other folks are having this same issue, it seems to be due to a faulty preview component in a Gatsby starter somewhere. Can you link to the starter you used? Would like to address it that source if we can.

**Comment by erezrokah** [comment]
Closing as stale
