### ISSUE TITLE
Widget using the Trix Editor

### ISSUE THREAD

**Issue by jclusso** [netlify/netlify-cms#2555]
*Is your feature request related to a problem? Please describe.**
Better rich text editing

**Describe the solution you'd like**
https://github.com/basecamp/trix

**Comment by talves** [comment]
This would be great for a custom widget. I will leave here for the one of the community can create. Of course, @jclusso , taking a stab at this by using one of the existing widgets as an example would be an option for you too.

**_Note_**: This couldn't take the place of the existing editor, because there needs to be the option for markdown output into the body of the markdown file.
