### ISSUE TITLE
Change MomentJS locale manually

### ISSUE THREAD

**Issue by saenglert** [netlify/netlify-cms#2578]
**Is your feature request related to a problem? Please describe.**
When saving a date(time) widget using a Moment format the resulting string is using English terms (default locale). I.e. `2019-08-23T12:45:23.136Z~ ` is formatted into `Friday, 23. August 2019`. While this is technically correct, in a page that's otherwise written in German this looks odd.

**Describe the solution you'd like**
Either a site wide option or an additional parameter to the widget that contains the desired locale would be awesome.

**Describe alternatives you've considered**
Writing a custom widget that does this but as this seems to me as a rather fundamental feature I wanted to ask if this is something you want to add or possible already have and I'm just to blind to find it.

**Comment by erquhart** [comment]
We would take a PR to change the date format in the CMS interface. If you're trying to change it for your site, we recommend handling formatting through your static site generator. But if you really want to output a formatted date/datetime string, the date/datetime widgets do accept **format**, **dateFormat** and **timeFormat** values in the config.

https://www.netlifycms.org/docs/widgets/#date

**Comment by neokree** [comment]
Is there any active development on this feature? 
I was also looking for a way to change the Moment.js locale for the `datetime` widget

**Comment by erezrokah** [comment]
Hi @neokree we try to work our way through the most requested features first:
https://github.com/netlify/netlify-cms/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

The issue with this is that the CMS doesn't bundle all of moment locales since it increases bundle size significantly.

There might be a way to set moment locale globally which should work for the date widget too:
```js
import moment from 'moment';
import 'moment/locale/ja';
moment.locale('ja');
```

But I haven't figured out a way to do access the moment instance bundled with the CMS yet.
It will take some time digging into it.

**Comment by neokree** [comment]
There is not a way to set an initial script that is loaded during CMS startup?

**Comment by erezrokah** [comment]
@neokree, please see here https://github.com/netlify/netlify-cms/pull/3458
