### ISSUE TITLE
NetlifyCMS for non Netlify hosting website.

### ISSUE THREAD

**Issue by vsirghii** [netlify/netlify-cms#2695]
How to use NetlifyCMS with a web site on AWS S3? In NetlifyCMS docs all the examples are for the site on Netlify. How about S3, what are the steps of setting the identity, etc? Google search doesn't give any specifics...
Regards,
Victor.

**Comment by erquhart** [comment]
The short answer is "its complicated". Netlify CMS works wherever you want it to, you just need to write your own code to connect to the services you prefer. Netlify is used because its super easy, anything else I would consider an advanced use case (Eg. a preference to use S3). I'm also coming up dry for Netlify CMS/S3 tutorials on Google.

**Comment by damian-tripbuddi** [comment]
I'm trying to get NetlifyCMS working with Amplify.

I was under the impression that it wouldn't be hard to get NetlifyCMS working with other hosting providers.

A little disappointing, as I was really keen to work with NetlifyCMS.

**Comment by erezrokah** [comment]
While not being a complete tutorial I think one can use [this repo](https://github.com/erezrokah/gatsby-netlify-cms-aws) as a reference.

The interesting bits are:
* Authentication: [backend](https://github.com/erezrokah/gatsby-netlify-cms-aws/tree/1ccb0cbe3ddd2db17ac60ee37a44197d397b7250/backend), [serverless.yml](https://github.com/erezrokah/gatsby-netlify-cms-aws/blob/1ccb0cbe3ddd2db17ac60ee37a44197d397b7250/serverless.yml#L72), [cms dynamic config](https://github.com/erezrokah/gatsby-netlify-cms-aws/blob/1ccb0cbe3ddd2db17ac60ee37a44197d397b7250/src/cms/index.js#L6) and [post deploy script](https://github.com/erezrokah/gatsby-netlify-cms-aws/blob/1ccb0cbe3ddd2db17ac60ee37a44197d397b7250/serverless-scripts/stackOutput.js#L64)
* Preview links: [bucket per preview](https://github.com/erezrokah/gatsby-netlify-cms-aws/blob/1ccb0cbe3ddd2db17ac60ee37a44197d397b7250/serverless-single-page-app-plugin/index.js#L299), [ci](https://github.com/erezrokah/gatsby-netlify-cms-aws/blob/1ccb0cbe3ddd2db17ac60ee37a44197d397b7250/.circleci/config.yml#L131) and [static cms config](https://github.com/erezrokah/gatsby-netlify-cms-aws/blob/1ccb0cbe3ddd2db17ac60ee37a44197d397b7250/static/admin/config.yml#L4)
* Hosting: [S3 and CloudFront](https://github.com/erezrokah/gatsby-netlify-cms-aws/blob/1ccb0cbe3ddd2db17ac60ee37a44197d397b7250/serverless.yml#L174) and [custom certificate](https://github.com/erezrokah/gatsby-netlify-cms-aws/blob/1ccb0cbe3ddd2db17ac60ee37a44197d397b7250/serverless.yml#L49)

**Comment by erezrokah** [comment]
Closing this. Please re-open if you have anymore questions

**Comment by zephyrz73** [comment]
I came across this issue while looking for hosting Netlify CMS on AWS rather than Netlify. I realized there weren’t many tutorials or examples to do that. In case others land on this issue and are wondering the same as me, I wrote a series of blog posts about this during my internship at Pulumi. Please checkout this [post](https://www.pulumi.com/blog/deploying-the-infrastructure-of-oauth-server-for-cms-app/). It’s part two of a 2-part series and specifically shows deploying a server that can do the OAuth authorization flow with GitHub etc.

**Comment by erezrokah** [comment]
This is great thanks. Very important resource we were missing.
I assume you're good with this PR https://github.com/netlify/netlify-cms/pull/4319/files (asking since it's not from your GitHub profile while still coming from a pulumi employee).

**Comment by praneetloke** [comment]
@erezrokah glad to hear it! I opened the PR on @zephyrz73's behalf just so I can respond to any PR comments not knowing the turnaround time for PR reviews for examples. :)

**Comment by zephyrz73** [comment]
@erezrokah Yeah, @praneetloke will help me out about the rest of the work needed for submitting my code as part of https://www.netlifycms.org/docs/examples/  because of the sad fact that tomorrow will be the end of my internship. @praneetloke is my mentor for the internship and helped me a lot during development.
