### ISSUE TITLE
Website doesn't display any content while display preview does (Hugo)

### ISSUE THREAD

**Issue by endormi** [netlify/netlify-cms#2761]
**Describe the bug**
When deploying a site the CSS gives an error:

```
Access to CSS stylesheet at 'https://endormi.io/css/coder.min.28d751104f30c16da1aa1bb04015cbe662cacfe0d1b01af4f2240ad58580069c.css' from origin 'https://5da9bf15c0cd28c348beafe0--endormi-portfolio.netlify.com' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.
```

 Weirdly enough checking the https://deploy-preview-15--endormi-portfolio.netlify.com/ works perfectly and https://endormi-portfolio.netlify.com/ doesn't.

Also the main site which is https://endormi.io, doesn't display anything. It tries to use my old code.

**To Reproduce**
1. Deploy site
2. Checking link

**Expected behavior**
Displays site and gets the css

**Applicable Versions:**

 - Git provider: GitHub
 - OS: Windows 10
 - Browser version  chrome 77.0.3865.120

**Comment by talves** [comment]
There is not an actual issue here. This is how CORS works.

> Weirdly enough checking the https://deploy-preview-15--endormi-portfolio.netlify.com/ works perfectly

Because it is using the `https://deploy-preview-15--endormi-portfolio.netlify.com/css/coder.min.28d751104f30c16da1aa1bb04015cbe662cacfe0d1b01af4f2240ad58580069c.css` instead of the cross domain link `https://endormi.io/css/coder.min.28d751104f30c16da1aa1bb04015cbe662cacfe0d1b01af4f2240ad58580069c.css`

You can inspect your page in the browser and track these using the network tab to see.

**Comment by endormi** [comment]
Okay, thanks 👍. I actually just fixed it. Now the issue that I have is my website doesn't display anything https://endormi.io and the preview deploy works https://master--endormi-portfolio.netlify.com/. So the issue is that it uses my old gatsby code which I now updated to Hugo. 

What are some possible fixes?

**Comment by talves** [comment]
I see your site ` https://endormi.io` just fine.

**Comment by talves** [comment]
I'm going to close this issue, because this repository is for `netlify-cms` exclusively. You can go to https://community.netlify.com if you continue to have any issues.
