### ISSUE TITLE
Date not added to new posts

### ISSUE THREAD

**Issue by nifl** [netlify/netlify-cms#29]
Creating new posts in the admin UI fails to prepend the date to the filename.

**Comment by biilmann** [comment]
This should work, but you'll need to set a slug configuration for the collection (since not all collections need the data prepended).

See the slug setting in the example Jekyll template:

https://github.com/netlify-templates/jekyll-netlify-cms/blob/master/admin/config.yml#L20

If that setting is in place and you're still not seeing the date prepended to the filename, it's a bug...

**Comment by nifl** [comment]
Thanks. I didn't have the slug setting and now this works for me. I'm using the template in this repo's readme. I didn't see this setting mentioned in the docs. It would be be great to have a section or wiki page on generator-specific config settings. I'm using Jekyll 3 currently.
