### ISSUE TITLE
Draft image not showing in preview pane

### ISSUE THREAD

**Issue by erquhart** [netlify/netlify-cms#3158]
**Describe the bug**

Images that are newly uploaded from the entry page are not shown in the preview pane.

**To Reproduce**

1. Open the [products page entry](https://gatsby-starter-netlify-cms-ci.netlify.com/admin/#/collections/pages/entries/products) in the Gatsby starter demo
2. Click "choose a different image" in the first image field
3. Upload and select a new image
4. Observe image is shown in the control panel but not in the preview pane

**Expected behavior**

Image should show in the preview pane.

**Additional context**

Note that previously uploaded images do show as expected in the preview pane.

**Comment by shmuelbarkin** [comment]
@erquhart this typically happens when the image is very large (in size). Currently Netlify CMS does not handle very large images well in the control panel.

**Comment by erquhart** [comment]
Thanks @shmuelbarkin , this is happening regardless of image size, and only impacts the preview pane (shows fine in control pane). Might be worth opening an issue if you’re seeing large images fail to upload/insert properly, though. You can also block users from uploading undesirably large images with the [`max_file_size` media library config](https://www.netlifycms.org/docs/beta-features/#image-widget-file-size-limit) (currently in beta).

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by barthc** [comment]
@erquhart  the issue is with the starter template, the preview is trying to pull the image via the image widget value, but the image is not uploaded yet, that's why previously uploaded images works. Pulling the image url via `getAsset`  [here](https://github.com/netlify-templates/gatsby-starter-netlify-cms/blob/master/src/cms/preview-templates/ProductPagePreview.js#L17) will solve the issue.
