### ISSUE TITLE
Add simple filesystem backend

### ISSUE THREAD

**Issue by Benaiah** [netlify/netlify-cms#329]
**- Do you want to request a *feature* or report a *bug*?**

New feature.

**- What is the current behavior?**

Currently there is no backend which uses the filesystem. This would be useful for local work and testing.

**- What is the expected behavior?**

There should be a backend available which calls a simple API that allows reading and writing from the filesystem. Netlify CMS should allow you to spin up a local filesystem-backed instance via an `npm` task.

**Comment by daddykotex** [comment]
Hey guys, I'm really interested in developing this feature. I'd like to know some of the tools you use when working with this project so I can have a similar setup.

I'm on MacOS and I'm familiar with Sublime, Atom, Intelli-J (or Webstorm). If you guys use linters or plugins for your editors to ease development, I'd like to know.

If nobody is already working on it, I'd gladly do this.

**Comment by daddykotex** [comment]
Well I just found that: https://github.com/netlify/netlify-cms/blob/master/CONTRIBUTING.md

And you address linting, so this should help!

**Comment by daddykotex** [comment]
Just realized that from the browser you don't have much access to the FS, how would you proceed?

**Comment by biilmann** [comment]
Would be an awesome contribution!

My thought was to create a cli tool within the cms to start a small server from your project folder that would expose the needed api....

**Comment by Benaiah** [comment]
@daddykotex yeah, our plan was to create a small Node server which would provide a simple API which would connect to the filesystem. You'd be able to start that locally and connect the CMS to it for both testing purposes and editing local files. For now we were thinking this would have the same functionality currently supported by the in-memory test backend (so no editorial workflow to start with, which should make that simpler).

I'd be happy to help out if you have any questions about or want any input on implementing this issue. Feel free to ping me here or on the Gitter at https://gitter.im/netlify/NetlifyCMS.

**Comment by daddykotex** [comment]
Ok, so this afternoon I started playing with it. I have a branch here: https://github.com/daddykotex/netlify-cms/tree/issue-329/filesystem

Of course, paths are hardcoded, but basically I can retrieve the posts via a small node server like you suggested:
```
#tab 1
npm run start
#tab 2
npm run fs
```

**Comment by daddykotex** [comment]
Note that I used `require` because I don't know much about `webpack` and it was holding me back.

**Comment by Benaiah** [comment]
@daddykotex are you still working on this? Let me know if you need any help, or if you want me to start tackling this myself. Thanks for your work so far!

**Comment by daddykotex** [comment]
Well, I don't know if you have looked but I wrote a small Node web server to list the files and fetch their content. The commit is there: https://github.com/daddykotex/netlify-cms/commit/1664265a53b0294f57d52b1455e08f0a170dfb4c

I just want to know if I'm heading in the right direction and and if not, what do you want me to change. I have problem running `npm run lint` on `master`. I don't know if it's expected or not but before I start polishing my MR I want to make sure I'm on the right track.

**Comment by Benaiah** [comment]
@daddykotex I have checked this out - it seems like a solid start. The `npm run lint` problems are known - @josephearl and I are working on that issue. I like the direction this is going, though it's obviously not finished yet. I was just checking in in case you didn't think you'd be able to continue with that work, as in that case I'd pick up this branch.

**Comment by daddykotex** [comment]
So far I have:

1. A webserver that allows listing and reading of files
2. A file-system backend implementation that uses the webserver
3. An example hugo static site along with it netflify-cms configuration

From my point a view, here's what's missing:

1. Use of webpack for the webserver implementation (I'm really short here)
2. Saving files via the webserver
3. Error handling in both the webserver and the file-system backend

Do you need anything else?

```
#tab 1, i've updated webpack-dev.conf to use fs-example
npm run start
#tab 2
# give the web root directory
npm run fs -- -d ~/workspace/netlify-cms/fs-example/ss-hugo/
```

**Comment by whizzter** [comment]
Just found netlify and it's really something similar to what i've had in mind myself (started hacking a bit on a clientside-CMS but it's nowhere near completion).

@daddykotex Is the listing/reading/etc following REST semantics?

One suggestion i think might be considered (that i thought as a starting point for my own project) would be to add a "blob" backend also, with a single HTTP(S) endpoint that uses Basic Auth and only supports GET/PUT operations for a JSON data blob. It might not be as flexible (and won't allow concurrent editing) but would be perfect for people starting to build applications since they wouldn't need to implement more than the bare basics in terms of communication and could then just render an application from the blob data.

**Comment by daddykotex** [comment]
You can check it yourself: https://github.com/daddykotex/netlify-cms/commit/682b4977fc4d7e45ce45de28eb3a034ccc96b793#diff-968972ca44958c715aa87a512b507ee9

There are only 2 endpoints and I completely forgot about this PR to be honest. 

There is two GET endpoints. One to fetch entries, one to fetch a file content. There is one POST endpoint to create file (BLOB) as you suggested. It's missing a lot of validation though.

**Comment by erquhart** [comment]
@daddykotex I forgot about this PR too, glad @whizzter commented.

This would definitely still be a great add! Took a quick look at the branch, here's a few considerations:

* The existing example still needs to run on `yarn start`, it's still the cheapest way to test the CMS itself from a static deployment. Probably drop the example altogether, good documentation should fill the gap.
* We have to validate and restrict fs operations heavily, eg., ensure that the server can't read or write above it's own parent directory. The CMS cannot be responsible for data loss, even in case of user error.
* Accept arguments like `-d`/`--directory` via the config instead of hardcoding to the cli.
* We originally expected to continue using git, probably via `node-git`, but I'm not against starting with straight read/write.
* Editorial workflow won't work as is, but again, that can be an improvement.

**Comment by erezrokah** [comment]
https://github.com/netlify/netlify-cms/pull/3217 resolves this
