### ISSUE TITLE
Inform user (or create redirect) when changing the title of a collection item

### ISSUE THREAD

**Issue by verythorough** [netlify/netlify-cms#336]
**- Do you want to request a *feature* or report a *bug*?**
Feature

**- What is the current behavior?**
This is somewhat dependent on the generator/build tool, but when a user changes the title of an item, the link for the item usually changes, too, breaking previous links. CMSs like WordPress automatically create redirects for this.

**- What is the expected behavior?**
Automatic redirects would be cool, but depend on a number of factors that aren't consistent across build tools & environments. A small nicety would be to just warn the user when saving a post edit with a title change.

**Comment by tech4him1** [comment]
I thought we kept the existing slug (file path) for a page when the title was changed?

**Comment by erquhart** [comment]
The file path doesn't change, but static site generators will often place generated files based on a slug that's partially composed of the title field.

Notifying users is potentially helpful, but handling redirects is compelling. It's certainly out of scope for Netlify CMS to directly handle this, but it can integrate with a static site generator, e.g. [Hugo aliases](https://gohugo.io/content-management/urls/#aliases), or with a static site's hosting platform, e.g. Netlify's [_redirects](https://www.netlify.com/docs/redirects/).

Considerations:

* Sometimes the url change won't matter - should the user be able to choose whether a redirect is created?
* Warn about the possibility of a URL change by default if no integration is in place?
* What happens when a new entry creation would collide with an existing redirect?

Redirects is something folks are used to a CMS handling, so it's worth discussing.

**Comment by KancerEzeroglu** [comment]
Hi,
I created a file with the title as `test` and I got this URL:
collections/posts/entries/folderA/2020-10-09-test
And then I've changed the title to `glass` and I got the same URL.

I think we can close this task as it invalid.
@erquhart WDYT?

**Comment by erezrokah** [comment]
Hi @KancerEzeroglu, thank you for looking into this.
I think the issue here is that some build processes look at the title instead of the filename thus will generate a different URL.

However I think this is out of scope of the CMS and is better handled by something like:
https://github.com/sw-yx/netlify-plugin-no-more-404

as doing so during the build process is more robust.

Closing the issue per my comment.
