### ISSUE TITLE
Having Issues Logging In

### ISSUE THREAD

**Issue by sdras** [netlify/netlify-cms#3587]
**Describe the bug**
This has happened a few times now, I can't log in with GitHub or my password, and then have to reset my password

**To Reproduce**
Try to log in via GitHub, and via old password.
Here is a reproduction:
https://drive.google.com/file/d/1doFPMkvxfliZ08KOatJSRIxvEZgoEb0P/view?usp=sharing

**Expected behavior**
Log in via either GitHub or old password and content loads.

**Applicable Versions:**
Running on netlify-www

**Additional context**
This issue happened before, but I didn't take a video before resetting the password last time.

**Comment by jlengstorf** [comment]
I hit this as well and had to reset my password.

**Comment by erezrokah** [comment]
I think I was able to create a reproduction, posting here to make sure it is the same issue.

1. Setup a Netlify site with Identity, `git-gateway` and CMS configured
2. Change Identity registration to invite only
3. Setup GitHub as an extremal provider
4. Invite a user via an email that is different from the user GitHub's account email (@sdras, @jlengstorf can you verify this?)
5. Create a password for the user via the email registration link
6. Visit the site and try to login via GitHub
7. See that the login fails (I'm assuming since the [emails don't match](https://github.com/netlify/gotrue/blob/49e0866b91fa6b28b098163765d513621c171c98/api/external.go#L117))
8. See that you're redirected to `<site>/admin/#/error=access_denied&error_description=Signups+not+allowed+for+this+instance`.
9. Try to login via the invited email and password.
10. See that you're redirected to the CMS, but to a `Not found` page.

> Clicking any other tab in the CMS will navigate to the proper page as the user is logged in

![login_issue](https://user-images.githubusercontent.com/26760571/79101286-e4ffcd00-7d70-11ea-882a-e171a850733e.gif)

**Comment by jlengstorf** [comment]
unless something changed with GitHub that I'm not aware of, my work and personal emails are attached to my GH account, so I don't believe this is an email mismatch problem — happy to pair up if it'll help diagnose?

**Comment by erezrokah** [comment]
Which one is the primary email? Looks like `gotrue` uses that one:
https://github.com/netlify/gotrue/blob/c9327d42aacc622c9dac493c8126f01f15ffc44d/api/provider/github.go#L85

**Comment by jlengstorf** [comment]
@erezrokah my Netlify email is _not_ the primary, but that seems like a pretty troubling failure, IMO

**Comment by erezrokah** [comment]
Yes, you're right - I'll create an issue for it in the `gotrue` repo, we already have a [fix up](https://github.com/netlify/netlify-cms/pull/3599) in the CMS regarding handling a successful email/password login after the external one fails.
We should probably show a better error message for the failure too, but that's a bit challenging to debug since external providers are not supported when working locally (https://github.com/netlify/netlify-identity-widget/issues/86).

**Comment by sdras** [comment]
Thanks for working on this Erez, great sleuthing as usual. Yep, my email for github is my personal email, and my work email is the invited one. I would assume that's fairly normal though, no? Most folks will have an existing GitHub account tied to their personal email and not their work account as an eng. :) I agree it's probably a gotrue failure, but unfortunately most people will not see it that way since CMS loads and just loads nothing, so we would need a way to deal with these types of failures that more graceful within the CMS, IMO.

**Comment by erezrokah** [comment]
Both of you are right, I'll check how the identity widget reports this failure and see if we can handle it in a better way. To provide a good error message we will need to have the widget report the provider used to login as the behaviour is different between providers and can also be caused by not inviting the user at all.

**Comment by erezrokah** [comment]
FYI, after looking into the `gotrue` code decided it might be simpler (and better) to just fix the underlying issue:
https://github.com/netlify/gotrue/pull/243
