### ISSUE TITLE
Pull requests and commits submitted through NetlifyCMS are not getting signed correctly

### ISSUE THREAD

**Issue by jeremyzilar** [netlify/netlify-cms#4033]
We are experiencing a few issues with our REPO since using Netlify + NetlifyCMS to manage our site builds and content.

### Pull requests and commits submitted through Netlify CMS are not getting signed correctly

[All of our pull requests](https://github.com/brooklynrail/brooklynrail-platform/pulls?q=is%3Apr+is%3Aclosed) that come via edits being made through our NetlifyCMS are being signed as `jeremyzilar` (that is me), when actually the edits (commits through the editorial workflow tool) are being made by other people on the team. [Here are our recent commits](https://github.com/brooklynrail/brooklynrail-platform/commits?author=catherineolson). They should all be from the `catherineolson`. I have not made an edit to the site in weeks.

![image](https://user-images.githubusercontent.com/395641/87823559-a0893f00-c841-11ea-814c-5b86c3fb23df.png)

Recent commits: https://github.com/brooklynrail/brooklynrail-platform/commits/master

---

**Background**
Our Netlify site is built using Hugo.
- Our repo: https://github.com/brooklynrail/brooklynrail-platform/
- Our site: https://brooklynrail.org/events _(note, we're using Netlify to build out just the events portion of Brooklynrail.org)_
- Our NetlifyCMS config https://github.com/brooklynrail/brooklynrail-platform/blob/master/themes/brooklynrail/static/workflow/config.yml
- This repo/site uses GIT LFS to manage the photos

**Comment by erquhart** [comment]
It's because you're using Git Gateway for auth. Using Git Gateway/Netlify Identity allows your editors to edit the site without having a GitHub account, so for GitHub specific operations like opening or merging PR's, it uses the user tied to your Git Gateway token. You'll notice the commits themselves are still tied to the editor's own email, and only the merge requests are associated with your user.

We've generally used a special GitHub "bot" account for this purpose, one not tied to a specific user, so it's clear that the opener/merger role is insignificant.

**Comment by erezrokah** [comment]
Just to add to @erquhart, the signed commits are due to the fact that GitHub auto signs each merge commit.

**Comment by jeremyzilar** [comment]
Thanks! I will explore our options for auth. Maybe this is just how it will have to be for now.
