### ISSUE TITLE
Filter Files in Collection

### ISSUE THREAD

**Issue by jholmes033169** [netlify/netlify-cms#407]
New behavior should be added to allow files to be filtered, within a collection, by markdown front matter attributes.

There are a number of use cases supporting the need for this feature. Many static file generators assemble all posts in a single folder... often a folder called "posts" or "_posts." However, any sophisticated blog may have multiple categories of posts... regular posts, landing pages, articles with minimal info, or articles requiring specific fields (author, address, category, etc.) that not all posts need.

Another case is simply to make writing articles easier on the poor folks who would otherwise have to look at hundreds of markdown files all grouped together. Filtered collections would allow them to see articles grouped by categories, even though they are in the same _posts directory.

The current behavior requires all articles to have all possible fields, when only a small subset of posts may need them.

**Comment by lmcorreia** [comment]
This could also prove handy as a crude way of doing some i18n on the entries. Instead of looking up for similar entries in different languages in completely different ways (almost a different method per generator), we could use this to find entries with the same `title` but different `language` fields.

Will try to implement a little something in a jiffy.
