### ISSUE TITLE
Curly apostrophe in title not being escaped in slug generation.

### ISSUE THREAD

**Issue by eugenefm** [netlify/netlify-cms#4212]
**Describe the bug**
If the user enters a curly apostrophe in the title of their post. That character is not escaped and is used in the filename and route. This leads to errors loading the post when trying to edit it.

**To Reproduce**
1. Add a new blog post with a curly apostrophe in the title `’`
2. Try to edit that blog post after saving it, and it will fail to load.
3. Notice that the filename includes that character unescaped.

**Expected behavior**
All special characters should be escaped in slug generation.

**Applicable Versions:**
netlify-cms-app 2.12.19
bootstrap.js:83 netlify-cms-core 2.30.3

**CMS configuration**
```
config: {
    backend: {
      name: 'bitbucket',
      repo: REPONAME,
      branch: 'master',
      auth_type: 'implicit',
      app_id: APPID,
      commit_messages: {
        create: 'Create {{collection}} “{{slug}}”',
        update: 'Update {{collection}} “{{slug}}”',
        'delete': 'Delete {{collection}} “{{slug}}”',
        uploadMedia: '[skip ci] Upload “{{path}}”',
        deleteMedia: '[skip ci] Delete “{{path}}”'
      }
    },
    publish_mode: 'editorial_workflow',
    load_config_file: false,
    local_backend: true,
    media_folder: 'static/img',
    public_folder: '/img',
```

**Comment by erezrokah** [comment]
See my comment here https://github.com/netlify/netlify-cms/pull/4244#issuecomment-687870023.

I recommend contacting Bitbucket support and following up here once you have a response from them.

**Comment by fitzage** [comment]
This character in a slug with a nuxt-content based setup causes nuxt to throw an error when visiting the page directly or refreshing it (vs clicking on it from a different part of the nuxt app). This error doesn’t seem to cause a problem when testing with `yarn dev` or when generating my static site locally (although the error does show up in the console). But when this error occurs when the site is deployed on Netlify it causes the page contents to disappear.

So I guess what I’m saying is that I’m resurrecting this dead thread to say that this behavior really is a bug, because it causes weird behavior elsewhere.

**Comment by fitzage** [comment]
I’m now seeing the ascii encoding option, which seems like the ticket. Carry on.
