### ISSUE TITLE
silent failure on save due to case of collection "Title" in config.yml 

### ISSUE THREAD

**Issue by client9** [netlify/netlify-cms#458]
I tested on cms.js v 4.2 and v3.22 in both latest safari and chrome.

Saving always failed (silently).  Looking in console I got:

<img width="357" alt="screen shot 2017-06-17 at 5 18 55 pm" src="https://user-images.githubusercontent.com/217179/27257172-497e8414-5381-11e7-8894-4609093ecf59.png">

Appears to be in:

```javascript
const slugFormatter = (template = "{{slug}}", entryData) => {
  const date = new Date();
  const identifier = entryData.get("title", entryData.get("path"));  <---- NULL
  return template.replace(/\{\{([^\}]+)\}\}/g, (_, field) => {
    switch (field) {
      case "year":
        return date.getFullYear();
      case "month":
        return (`0${ date.getMonth() + 1 }`).slice(-2);
      case "day":
        return (`0${ date.getDate() }`).slice(-2);
      case "slug":
        return slug(identifier.trim(), {lower: true});  <---- EXPLODE HERE
      default:
        return slug(entryData.get(field, "").trim(), {lower: true});
    }
  });
```

because my `config.yml` has this

```yaml
    fields:
      - {label: "Title", name: "Title", widget: "string"}
```

i.e.  `name: Title` not `name: title`

Seems like this could be made more robust or more clear on what failed.

thanks,

n

**Comment by erquhart** [comment]
Hmm that slug config should simply change the slug to lowercase, it's not a validation check. Having a look.

**Comment by erquhart** [comment]
Ah, I see, we're only getting lowercased title in the first place. We'd definitely take a PR for this.

**Comment by eamonnbell** [comment]
I'd be happy to take a crack at this as a first contribution. There's a couple of ways out - I'd like to go with what's most consistent with team's roadmap.

When the field name is set to `"Title"` as in the steps to repro, the call to `entryData.get("title", ...)` fails through to the second argument (`notSetValue`), which is another `.get()`. Next, the value keyed to `"path"` in the `entryData` map is never being set (at least, not when using the test-repo backend). So this fails too, this time with no `notSetValue`. I'm not sure if the value keyed to `"path"` is ever set when using the `github` backend.

Wiring up the `entryData` `Map`  to be case-insensitive is probably to be avoided.

A quick fix would be to provide a `notSetValue` for the second `.get()` so that in the worst case some identifier (e.g. UUID) is generated and constructing the slug goes ahead without notifying the user. But I don't think nesting `.get()` like this is good -- `notSetValues` should not be dynamically set.

Better would be to put the `identifier` assignment into the `case: "slug"` block, since it's only used there, and then throw an exception if a valid identifier can't be found.

It could also be addressed in by writing a new validation rule for config.yml, by checking that there is a `"title"` field in the collection spec if the slug template includes `{{slug}}` or is unset.

**Comment by erquhart** [comment]
Honestly, since we're just trying to allow `title` to be uppercase, we're probably best off adding a case for that when assigning `identifier`.
