### ISSUE TITLE
Cannot login with Github, on a live domain, when cms in Open authoring mode, but works fine on localhost

### ISSUE THREAD

**Issue by hugurp** [netlify/netlify-cms#4731]
Hello!

**Describe the bug**
When netlify-cms is setup in `open_authoring` publishing mode, login with github works locally, but not when the site is live (github page + custom domain).

**To Reproduce**

([jsbin example](https://jsbin.com/laralukaqe/edit?html,js,console,output))

- A minimal netlify-cms setup with a repository setup for open authoring, and a default collection (steps here: https://www.netlifycms.org/docs/open-authoring)

When clicking the login with github button, a new browser page opens (not new tab), with the folowing URLs:
- on localhost: `https://api.netlify.com/auth/done?code=7eee<longstring>&state=eyJ0e<longstring>`
- on live: `https://api.netlify.com/auth?provider=github&site_id=companies.joblist.city&scope=public_repo`

After this, localhost succeeds, and live blocks on a api.netlify.com error:
```
No Auth Provider Found
Make sure you've configured the API credentials for Github from the Access part of your Netlify site dashboard.
```

**Expected behavior**
Able to log in locally and when the site is live, in open authoring mode, and without netlify.com (just netlify-cms open authoring and a github repo).

**Applicable Versions:**
Tested from latest and down on a few patch/minor versions, it does not seem to work, except locally, where everything is good.

**CMS configuration**
- live version (non minified code): https://companies.joblist.city
- admin index html: https://github.com/joblistcity/companies/blob/master/edit/index.html
- admin index js: https://github.com/joblistcity/companies/blob/master/edit/options.js
- root repo: https://github.com/joblistcity/companies/

**Additional context**
- The netlify identity widget should not be required as it works locally.
- (edit) tested with and without github `graphql` parameter, and both work locally, and not live. Keeping in right now, because it is making a lot less request to the Github api.

**Comment by erezrokah** [comment]
Hi @hugurp, did you follow [step 1](https://docs.netlify.com/visitor-access/oauth-provider-tokens/#using-an-authentication-provider) in https://www.netlifycms.org/docs/github-backend linked from https://www.netlifycms.org/docs/open-authoring/?

Using a GitHub backend requires a backend service to facilitate authentication since GitHub doesn't support implicit auth.
You can set one up [using Netlify](https://docs.netlify.com/visitor-access/oauth-provider-tokens/#using-an-authentication-provider) or use one of the [community provided solutions](https://www.netlifycms.org/docs/external-oauth-clients/).

It works on `localhost` since Netlify provides a test GitHub OAuth server when running locally to make development easier.

**Comment by hugurp** [comment]
Ah no!
I did not, I thought it was independent from the Github backend and netlify services.
Will try this, and I guess it should work.

Sorry for the wrong-issue then.

**Comment by hugurp** [comment]
The issue above was not a bug but a misunderstanding from my side.

To sum it up:

`netlify-cms` with `open-authoring`:
- needs to use github backend (with or without graphql)
- this means that you need a backend service for handling user authentication against github api (middleware)
- for this reason, it is "easier" to host the site serving the netlify-cms instance on netlify.app servers, as it comes with this authentication middleware out of the box (`Site settings > Access control > OAuth > Authentication Providers > Install Provider "github" < paste in github app id and private key`). Without this middleware it cannot be hosted on github pages (this issue; with or without custom domain).
- otherwise, you need to host this middleware yourself.

Thanks for your help!

**Comment by VojtechPetr** [comment]
Hi, I get into this problem as well. I have setup my config.yml as follow: 

backend:
  name: github
  repo: VojtechPetr/MeBS-Hodonin
  branch: main
  auth:
    client_id: 'Ov23li4P1rJmx2UWaWmP'
    scope: 'repo'
    base_url: 'https://mebs-hodonin-oauth.vercel.app'
    auth_endpoint: 'auth'

I tried to follow the description here and setup as well a backend service from here: https://github.com/vencax/netlify-cms-github-oauth-provider. My website is deployed in Vercel. As for @4www , locally it works fine, but once deployed I got this "Not found" new browser page:
![obrazek](https://github.com/user-attachments/assets/669da8a9-5a32-4a45-8463-87717891f029)


It's starting to making me crazy! Is a week, that I am working around, but without success. Any advice? I deployed the backend service, in Vercel I setup these env. variables:
![obrazek](https://github.com/user-attachments/assets/11b2bfff-95c3-47d0-b15e-4ad0d7c30d22)
which corresponds to the GitHUb OAuth app. The REDIRECT_URI in Vercel correspond to the Authorization callback URL in GitHub OAuth app "https://mebs-hodonin-oauth.vercel.app/callback". Am I overviewing something? Or where is the problem?

This is the console output:
![obrazek](https://github.com/user-attachments/assets/803eafc2-4a81-455b-948d-79068ecb2771)
Here translated ->
03:53:51.525 Redirected to https://www.bytovka.cz/admino/index.html
03:53:51.592 GET https://www.bytovka.cz/admino/index.html
03:53:51.723 GET https://www.bytovka.cz/admino
03:53:51.942 Removing unpermitted intrinsics
03:53:52.032 GET [https://unpkg.com/decap-cms@^3.1.2/dist/decap-cms.js](https://unpkg.com/decap-cms@%5E3.1.2/dist/decap-cms.js)
03:53:52.717 GET https://unpkg.com/decap-cms@3.3.3/dist/decap-cms.js
03:53:53.644 GET https://www.bytovka.cz/favicon.ico
03:53:53.755 decap-cms-app 3.3.3
03:53:53.765 Unknown pseudo-class or pseudo-element “-ms-track”. Rule set ignored due to bad selector.
03:53:53.765 Unknown pseudo-class or pseudo-element “-ms-fill-lower”. Rule set ignored due to bad selector.
03:53:53.765 Unknown pseudo-class or pseudo-element “-ms-thumb”. Rule set ignored due to bad selector.
03:53:53.765 Unknown pseudo-class or pseudo-element “-ms-thumb”. Rule set ignored due to bad selector.
03:53:53.765 decap-cms-core 3.4.2
03:53:53.766 Using config file path: "https://www.bytovka.cz/admino/config.yml"
03:53:53.768 decap-cms 3.3.3
03:53:53.780 XHR GET https://www.bytovka.cz/admino/config.yml
03:53:54.318 Start ajax tracing with delay of '0'.
03:53:54.388 Source map error: Error: NetworkError when attempting to fetch resource.
Source URL: https://unpkg.com/decap-cms@%5E3.1.2/dist/decap-cms.js
Source map URL: decap-cms.js.map [Find out more]
