### ISSUE TITLE
Upgrade to Webpack 3

### ISSUE THREAD

**Issue by bdougie** [netlify/netlify-cms#478]
I know the upgrade to Webpack 2 was just completed in #451 but since Webpack just came out it might be worth going up one more level to capture some built-in performance improvements. It is also reported that there are no breaking changes in Webpack 3, so the process should be as easy updating the package.json

https://medium.com/webpack/webpack-3-official-release-15fd2dd8f07b

**Comment by KraigWalker** [comment]
I have this working on a local branch. It was a bit of a hassle though. The issue is not so much upgrading webpack, but some of the plugins used are still in release candidate for their webpack compatible versions - namely `extract-text-plugin` which is in rc2. React Hot Loader is also in rc and yarn seems to be unable to find it with a normal yarn install command. I had to manually `npm install` the package by name and version tag.

**Comment by erquhart** [comment]
Okay - if that's the case, we can wait a bit and let versions stabilize.
