### ISSUE TITLE
Authentication

### ISSUE THREAD

**Issue by greatwarlive** [netlify/netlify-cms#482]
Is there anyway you can stop certain people accessing your CMS through authorising application, as otherwise any one can make posts?

**Comment by erquhart** [comment]
The CMS currently uses GitHub's permissions. If someone has read access in GitHub (this is everyone if your repo is public), they have read access in the CMS. But they can only make changes in the CMS if they have permissions to make changes (eg. push access) on your repo. Otherwise they'll get an error when they try to save a change.

#323 covers limiting CMS GitHub login to users with push access, closing in favor of that.
