### ISSUE TITLE
componentWillReceiveProps

### ISSUE THREAD

**Issue by rolfea** [netlify/netlify-cms#483]
**- Do you want to request a *feature* or report a *bug*?**
Bug
**- What is the current behavior?**
The EntryPage container seems to be firing the `componentWillReceiveProps` method 3 times before any user action.
**- If the current behavior is a bug, please provide the steps to reproduce.**
If you log the method, you can see in the dev. console that it fires three times on page load:
```
// EntryPage.js
componentWillReceiveProps(nextProps) {
    console.log("foo");
...
}
```
**- What is the expected behavior?**
I imagine that these are unintentional state changes or a "mini race-condition" that is causing this. I would imagine that 1 or 0 times would be the expected amount of calls to this method prior to user interaction with the page.
**- Please mention your node.js, and operating system version.**
Node  8.1.3, MacOS 10.12

**Comment by erquhart** [comment]
Thanks @rolfea, race condition sounds about right.

**Comment by rolfea** [comment]
@erquhart  
Since this is somewhat related to the fix I'm trying to add for https://github.com/netlify/netlify-cms/issues/286, I'm happy to work on this as well

**Comment by erquhart** [comment]
That would be great!

**Comment by tech4him1** [comment]
This is still a bug in 1.0.2, and it gets called five times now.

**Comment by tech4him1** [comment]
@erquhart @Benaiah Is this pretty much a non-issue?

**Comment by erquhart** [comment]
@tech4him1 just a performance thing, but it could be more troublesome than we know. There are definitely oddities in our state management, and it manifests at some points in the app.

This particular issue exists because we haven't taken a top-down look at which components should update when. Implementing `shouldComponentUpdate` in certain top level components could stop child components from receiving redux store updates, so we need to be careful when addressing.

**Comment by erezrokah** [comment]
Closing as stale
