### ISSUE TITLE
Rebuild image/file widget with Uppy

### ISSUE THREAD

**Issue by vnourdin** [netlify/netlify-cms#4965]
**Is your feature request related to a problem? Please describe.**
File uploads management should be handled by **a dedicated tool**, to bring good **features** and more **resiliency**.
[Uppy](https://github.com/transloadit/uppy) seems appropriate as it is **made to be integrated** and is well maintained.

**Describe the solution you'd like**
As described in [#2243](https://github.com/netlify/netlify-cms/issues/2243), using a dedicated library to manage uploads would solve a bunch of main issues about file or images upload.
I think Uppy is a better candidate than Filepond, as its code is **already divided in modules**, so we could easily use `@uppy/core` with Netlify CMS UI.

**Additional context**
You can find screenshots and documentation on the [Uppy website](https://uppy.io/).

**Comment by vnourdin** [comment]
@owenhoskins already gave a chance to Uppy in [#1032](https://github.com/netlify/netlify-cms/issues/1032), but this was discontinued, any idea why?

**Comment by erezrokah** [comment]
Hi @vnourdin it looks like it hit a wall because some limitations we had with uploading and deleting multiple files in a single commit.
I believe those limitations don't exist anymore as our backend implementations now support that.

It would be great to pick up that work and open a PR for it.

**Comment by mklueh** [comment]
Running into this "issue" as well. The feature would really be nice to have, as it is really time consuming to upload a bunch of images. Same goes for the selection for example, of the list widget. You need to add each image one by one

**Comment by patagoniapy** [comment]
Allowing the ability to add multiple images at once would really help supercharge the ability to build shippable products on Netlify CMS, as currently I am more reluctant to provide a client with a product that only allows them to add images one by one.

**Comment by erezrokah** [comment]
Hi @patagoniapy, agreed. It would be great to have this functionality if someone is willing to submit a PR for it.

**Comment by erezrokah** [comment]
Hi all 👋  I've made an attempt to add an external media library based on Uppy.

You can see the branch [here](https://github.com/netlify/netlify-cms/tree/feat/uppy) and the [deploy preview](https://feat-uppy--cms-demo.netlify.app/#/collections/posts).
Please note I tested that branch only with a local backend.

Unfortunately it doesn't look like Uppy is a good candidate yet. It's an amazing file uploader, but lacking features required to be a complete media library.
For example, loading existing files is not officially supported. I was able to do it based on [this issue](https://github.com/transloadit/uppy/issues/1112), but it adds existing files as already uploaded ones instead of being an integral part of a media library.
Also, it seems nested directories are not supported.

See also https://github.com/transloadit/uppy/issues/450.

I'm closing the issue, and will try to look at https://github.com/netlify/netlify-cms/issues/2243 as well.

If you have suggestions on making Uppy suitable for the CMS, please comment on the issue and we can re-open it.
