### ISSUE TITLE
Image uploading does not work in editor

### ISSUE THREAD

**Issue by kennedyrose** [netlify/netlify-cms#497]
I am able to upload images just fine when I toggle on markdown. But images won't show up at all in the rich text editor after adding them via `+` -> `Image`.

If I add them while in the rich text editor and switch over to markdown, it doesn't even show up in markdown. Currently the only way I can add images is in markdown mode.

I'm on macOS, tested with Chrome, Safari, and Firefox.

**Comment by erquhart** [comment]
I'm seeing this working: https://cms-demo.netlify.com/#/collections/posts/entries/new

What version are you using?

**Comment by kennedyrose** [comment]
It works for me in that demo, but not when I deploy the default [Hugo test drive app](https://www.netlifycms.org/docs/test-drive/) from the docs or when I use the code provided from the [quick start](https://www.netlifycms.org/docs/quick-start/).

Looks like the unpkg files in the demo are using 0.4.3

**Comment by erquhart** [comment]
Do you have a public deploy? I can take a look if so.

**Comment by kennedyrose** [comment]
I do: https://github.com/kennedyrose/kaldi-hugo-cms-template

Thanks!

**Comment by erquhart** [comment]
@kennedyrose I totally dropped the ball on this one, sorry!!

The issue here is the Kaldi template itself was created around an old CMS implementation that supported multiple media folders, so editing the template images doesn't work. This definitely needs to be addressed, but in the Kaldi template repo: https://github.com/netlify-templates/kaldi-hugo-cms-template, or the Netlify Identity variant: https://github.com/netlify-templates/one-click-hugo-cms
