### ISSUE TITLE
datetime widget format is not respected

### ISSUE THREAD

**Issue by rriemann** [netlify/netlify-cms#529]
**- Do you want to request a *feature* or report a *bug*?**

Bug

**- What is the current behavior?**

A field in the config.yml  such as

```yml
{label: "Publish Date", name: "date", widget: "datetime", format: "YYYY-MM-DD hh:mma"}
```

leads to an output:

    date: 2017-08-15T13:33:26.984Z

The output does not match the given format.

**- If the current behavior is a bug, please provide the steps to reproduce.**

Check out these repos:
- output: https://github.com/beta-europe/beta-europe.github.io/commit/d0e8dd21e1d94d29f4cb8c0e84ac0541e9ab68ee#diff-e743088db72d471d9ac3936dbfe70940R3
- config: https://github.com/beta-europe/cms-admin/blob/7d2feb0d2ea36cda4b924f88877713118f04b35b/config.yml#L19

**- What is the expected behavior?**

    date: 2017-08-15 13:33Wed

**- Please mention your node.js, and operating system version.**

Firefox Nightly (57) with https://unpkg.com/netlify-cms@^0.4/dist/cms.js

**Comment by erquhart** [comment]
@Benaiah is working on this, turned out to be non-trivial.

Benaiah can you give a quick update here?

**Comment by Benaiah** [comment]
Actually respecting the datetime format is pretty doable, and already implemented by myself and Matt. The UI, on the other hand, has some issues due to the limited API of the `DateTime` component we're wrapping. At this point I'm OK with merging the PR Matt and I have been working on (#842) once it's ready and living with the UI issues until we can fix the dependency.

**Comment by erquhart** [comment]
Yeah I ended up merging and releasing that right after my comment, we can close this.
