### ISSUE TITLE
Trying to get in touch regarding a security issue

### ISSUE THREAD

**Issue by JamieSlome** [netlify/netlify-cms#5598]
Hi there,

I couldn't find a `SECURITY.md` in your repository and am not sure how to best contact you privately to disclose a security issue.

Can you add a `SECURITY.md` file with an e-mail to your repository, so that our system can send you the vulnerability details? GitHub suggests that a [security policy](https://docs.github.com/en/code-security/getting-started/adding-a-security-policy-to-your-repository) is the best way to make sure security issues are responsibly disclosed.

Once you've done that, you should receive an e-mail within the next hour with more info.

Thanks! (cc @huntr-helper)

**Comment by Treefogg** [comment]
I thought I was just being followed by the thread I didn’t realize you were talking directly to me

***@***.***    Email



Sent from Yahoo Mail for iPhone


On Friday, July 9, 2021, 15:20, Jamie Slome ***@***.***> wrote:




Hi there,

I couldn't find a SECURITY.md in your repository and am not sure how to best contact you privately to disclose a security issue.

Can you add a SECURITY.md file with an e-mail to your repository, so that our system can send you the vulnerability details? GitHub suggests that a security policy is the best way to make sure security issues are responsibly disclosed.

Once you've done that, you should receive an e-mail within the next hour with more info.

Thanks! (cc @huntr-helper)

**Comment by erezrokah** [comment]
Hi @JamieSlome, closing this as a duplicate of https://github.com/netlify/netlify-cms/issues/5570

**Comment by JamieSlome** [comment]
No worries, and apologies for the duplication!
