### ISSUE TITLE
Failed to load config.yml when /admin without ending slash

### ISSUE THREAD

**Issue by inwardmovement** [netlify/netlify-cms#5688]
"Failed to load config.yml" when the url is `.../admin` without ending slash. (https://algosphere.org/admin)
It is ok with ending slash: `.../admin/` (https://algosphere.org/admin/)

[repo/config/versions](https://github.com/algosphere/algo-website/tree/main/static/admin)

**Comment by erezrokah** [comment]
Hi @inwardmovement, I don't believe this is related to the CMS, but to how your site is deployed. 

For example, https://www.netlifycms.org/admin works with or without the `/`.

As I've seen it before with Hugo based sites, you might have better results contacting their support.

Closing, please comment if you have any other questions

**Comment by frederik-station** [comment]
Same problem using Astro. Looks like the decap-cms.js script appends '#/' to the URL which causes a problem if the URL doesn't end with a slash.

Saw in the [Astro docs](https://docs.astro.build/en/guides/cms/decap-cms/#configuration) that it can be fixed by explicitly stating the config path by adding this link tag to the head:
`<link href="/admin/config.yml" type="text/yaml" rel="cms-config-url" />`
