### ISSUE TITLE
multiple repos for a single website.

### ISSUE THREAD

**Issue by drortirosh** [netlify/netlify-cms#6199]
I have a site that is built from two github databases.
one of the is the actual website documents. the other is a project code, but we auto-generate documentation on it, and want to keep it up to date.
(currently, we do manual "git clone" of the 2nd site to generate the code for it)

I need to trigger a netlify build when the 2nd repo is modified.

**Comment by erezrokah** [comment]
Hi @drortirosh, can you please follow the [feature request template](https://github.com/netlify/netlify-cms/issues/new?assignees=&labels=type%3A+feature&template=feature_request.md&title=Please+replace+with+a+clear+and+descriptive+title)?

I'm having a hard time if this is a request for Netlify CMS, or Netlify the platform.
If it's the latter please submit your question in https://answers.netlify.com/

**Comment by martinjagodic** [comment]
Hi, we believe that you have a problem, but in order for anybody to help you, you need to provide as much detail as possible. The issue template contains the bare minimum of what is required (how to reproduce, expected behaviour, screenshots, etc..).

I'm closing this issue for now. If the problem persists, please open a new issue with all of the details filled out. Also, before posting a new issue, please verify that everything is all right with your environment (computer, internet, browser) and verify whether this issue was already reported by someone else. For general help, please turn to our [Slack](https://decapcms.org/chat).
