### ISSUE TITLE
Profile pict in editor is ridicoulsly big and on top of editor tools

### ISSUE THREAD

**Issue by getdirty75** [netlify/netlify-cms#6322]
![ggg](https://user-images.githubusercontent.com/13219798/159479754-98a47ee3-f637-48db-94c4-c3348db0e6c9.jpg)

humm , what else you want ? 
My team mates cant work , cant edit, cant use widgets tools .... 

just add a class on profile pict .....

**Comment by martinjagodic** [comment]
Hi @getdirty75, we believe that you have a problem, but in order for anybody to help you, you need to provide as much detail as possible. The issue template contains the bare minimum of what is required (how to reproduce, expected behaviour, screenshots, etc..).

I'm closing this issue for now. If the problem persists, please open a new issue with all of the details filled out. Also, before posting a new issue, please verify that everything is all right with your environment (computer, internet, browser) and verify whether this issue was already reported by someone else. For general help, please turn to our [Slack](https://decapcms.org/chat).
