### ISSUE TITLE
Required/optional fields are not clearly marked

### ISSUE THREAD

**Issue by verythorough** [netlify/netlify-cms#650]
**- Do you want to request a *feature* or report a *bug*?**
bug

**- What is the current behavior?**
In the editor UI, required and optional fields look the same. However, if required fields are left empty, saving fails (with little feedback about why, but that's filed in #649).

**- What is the expected behavior?**
It would be nice to let users know up front which fields are required. Since fields are automatically required by default, this could mean that only the optional ones are marked, though it probably makes the most sense to go with the standard UI where there's a message at the top indicating that fields with an `*` are required, and adding the `*` to any required fields.

**- Please mention your CMS, node.js, and operating system version.**
Applies to all versions.

**Comment by rasikapohankar** [comment]
Hi, I'd like to work on this.

**Comment by Benaiah** [comment]
@rasikapohankar awesome! Our contributor guide is at https://github.com/netlify/netlify-cms/blob/master/CONTRIBUTING.md - is there any more info you need to get started? Feel free to join the [Gitter channel](https://gitter.im/netlify/NetlifyCMS) to chat if you'd like - the maintainers (@erquhart, @tech4him1, and myself) are in there often.

**Comment by erquhart** [comment]
cc/ @neutyp

**Comment by hcavalieri** [comment]
First of all, although most of the editor's fields are required, I'd rather highlight them when they're required - and therefore "pollute" the user's experience a little more - than **risking reducing the user's propension to fill an optional field** when it's explicited and highlighted that they could get away without filling it.

As editing pages in the CMS tend to be packed with different fields for different purposes, most of them require a lot of scrolling. For this reason, using the "regular" required field approach wouldn't work as the user might need to scroll back and fill another form when they learn it's required (see below - makes sense?). We could of course add a "* _Indicates required fields_" to the bottom of each field, but then it'd be repetitive.

![regular required field](https://user-images.githubusercontent.com/27744332/34017441-eb14f9d4-e10c-11e7-963a-a8a713f2a14d.PNG)

As for a floating, fixed information section would fill too much of the precious space inside the editor. However, the **top bar is barely touched in the middle**, so there's plenty of space to put it there, hence my first suggestion:

![group 1](https://user-images.githubusercontent.com/27744332/34017446-f8fc2f18-e10c-11e7-952e-98cbc695aa3b.png)


Pros and cons of this approach:

1. Pros:
    - It'd be more **intuitive** and explicit for newcomers.
    - It wouldn't make the editor much visually heavier
1. Cons:
    - It could draw more attention than needed/necessary;
    - It might conflict with the current puprple on focus effect of the fields

Another very popular approach is to **add an icon** or an asterisk next to the label of the field and add a **tooltip on hover**.

![group 2](https://user-images.githubusercontent.com/27744332/34017457-04de1062-e10d-11e7-930f-3c726cfb40f9.png)


Pros and cons of this approach:

1. Pros:
    - In my opinion it's more approachable and visually appealing;
    - It doesn't force old users to be exposed to an **extraneous line of text** every time they're writing something.
1. Cons:
    - It might not be so intuitive for non-tech savyy people;

A third one, which is no more than a simple variation of the second, would be with a card above the field that would only appear when the field scrolls into the middle of the view. I think it'd be a cool effect that would become annoying really fast if done wrong. It'd have to be very subtle, that's why the transparent color:

![group 7](https://user-images.githubusercontent.com/27744332/34017453-00c168ee-e10d-11e7-9492-017fb7854af8.png)


The picture may be a bit off, it's just a quick sketch, but basically the tip of the cards would appear outside and, when hovered, cover part of the inside with the information. It wouldn't be too heavy and is almost cool, we just gotta refine it.

I've ran out of ideas and time, but I'll think of more :)

**Comment by rasikapohankar** [comment]
Hi, I originally planned to work on this during October, I did not anticipate the load from school and could never complete this. Apologies for leaving this hanging. I had installed the tool from the instructions in the contributing guide and had started to look through the code, however, I didn't get very far.

Has someone else started work on this? If not, I would like to continue and will start in the next week.

**Comment by neutyp** [comment]
I'd like for us to consider the input title 'ear' as well as it's border turn red upon attempted save with an uncompleted required field. I had meant to put this in 1.0 but ran out of time. 

That said, we still need to solve for how to visualize required fields BEFORE you attempt to save.

**Comment by erquhart** [comment]
Honestly, considering that [we're settled](https://github.com/netlify/netlify-cms/issues/464#issuecomment-348311188) on required-by-default as the norm, sans draft related caveats, we should consider calling out optional fields instead.

I really think we can pull this off with just the word "Optional" in small gray text next to the label of each optional field.

**Comment by erquhart** [comment]
Fixed in #1955.
