### ISSUE TITLE
TypeError: e.split is not a function

### ISSUE THREAD

**Issue by KOD892** [netlify/netlify-cms#6534]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Applicable Versions:**
 - Netlify CMS version: `netlify-cms@2.10.192`
 - Git provider: `git-gateway`
 - Browser version: `Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:103.0) Gecko/20100101 Firefox/103.0`

**CMS configuration**
```
backend:
  name: git-gateway
  branch: main
media_folder: public/assets/img/uploads
public_folder: /assets/img/uploads
collections:
  - name: gallery
    label: Gallery
    folder: src/gallery-photos
    create: false
    fields:
      - label: Upload an image
        name: links
        widget: markdown
        default: blog
      - label: Tags
        name: tags
        widget: hidden
        default:
          - galleryPhoto
      - label: Title
        name: title
        widget: hidden
        default:
          - photos
    publish: true
    type: folder_based_collection
    sortable_fields:
      - commit_date
      - commit_author
    view_filters: []
    view_groups: []
publish_mode: simple
slug:
  encoding: unicode
  clean_accents: false
  sanitize_replacement: "-"
isFetching: false
error: null

```

**Additional context**

**Comment by martinjagodic** [comment]
Hi @KOD892, we believe that you have a problem, but in order for anybody to help you, you need to provide as much detail as possible. The issue template contains the bare minimum of what is required (how to reproduce, expected behaviour, screenshots, etc..).

I'm closing this issue for now. If the problem persists, please open a new issue with all of the details filled out. Also, before posting a new issue, please verify that everything is all right with your environment (computer, internet, browser) and verify whether this issue was already reported by someone else. For general help, please turn to our [Slack](https://decapcms.org/chat).
