### ISSUE TITLE
TypeError: e.replace is not a function

### ISSUE THREAD

**Issue by Shady-Prakash** [netlify/netlify-cms#6543]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Applicable Versions:**
 - Netlify CMS version: `netlify-cms@2.10.192`
 - Git provider: `gitlab`
 - Browser version: `Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.127 Safari/537.36`

**CMS configuration**
```
backend:
collections:

**Comment by martinjagodic** [comment]
Hi @Shady-Prakash, we believe that you have a problem, but in order for anybody to help you, you need to provide as much detail as possible. The issue template contains the bare minimum of what is required (how to reproduce, expected behaviour, screenshots, etc..).

I'm closing this issue for now. If the problem persists, please open a new issue with all of the details filled out. Also, before posting a new issue, please verify that everything is all right with your environment (computer, internet, browser) and verify whether this issue was already reported by someone else. For general help, please turn to our [Slack](https://decapcms.org/chat).
