### ISSUE TITLE
Please replace with a clear and descriptive title

### ISSUE THREAD

**Issue by Moodora** [netlify/netlify-cms#6547]
When using the text editor to edit the body of a markdown file, we cannot use the accent "^" (eg: ê or ô). It sends the writer to the end of the paragraph or removes the letter with the accent. It seems that there is no workaround :

https://recordit.co/QFdrFQzjlV

Browser : Firefox 104.0.1 and Chrome 105.0.5195.102 
Technology : HUGO 102
Netlify version/package : https://unpkg.com/netlify-cms@^2.0.0/dist/netlify-cms.js

**Comment by martinjagodic** [comment]
Hi @Moodora, we believe that you have a problem, but in order for anybody to help you, you need to provide as much detail as possible. The issue template contains the bare minimum of what is required (how to reproduce, expected behaviour, screenshots, etc..).

I'm closing this issue for now. If the problem persists, please open a new issue with all of the details filled out. Also, before posting a new issue, please verify that everything is all right with your environment (computer, internet, browser) and verify whether this issue was already reported by someone else. For general help, please turn to our [Slack](https://decapcms.org/chat).
