### ISSUE TITLE
SyntaxError: Expected ',' or '}' after property value in JSON at position 81

### ISSUE THREAD

**Issue by caroethompson** [netlify/netlify-cms#6582]
Error during captioning of images in Arabic language

**Screenshots**

**Applicable Versions:**
 - Netlify CMS version: `netlify-cms-app@2.15.72`
 - Git provider: `gitlab`
 - Browser version: `Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/105.0.0.0 Safari/537.36`

**Comment by martinjagodic** [comment]
Hi @caroethompson, we believe that you have a problem, but in order for anybody to help you, you need to provide as much detail as possible. The issue template contains the bare minimum of what is required (how to reproduce, expected behaviour, screenshots, etc..).

I'm closing this issue for now. If the problem persists, please open a new issue with all of the details filled out. Also, before posting a new issue, please verify that everything is all right with your environment (computer, internet, browser) and verify whether this issue was already reported by someone else. For general help, please turn to our [Slack](https://decapcms.org/chat).
