### ISSUE TITLE
TypeError: can't access dead object

### ISSUE THREAD

**Issue by ankitsinghaniyaz** [netlify/netlify-cms#6592]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Applicable Versions:**
 - Netlify CMS version: `netlify-cms@2.10.192`
 - Git provider: `git-gateway`
 - Browser version: `Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:106.0) Gecko/20100101 Firefox/106.0`

**CMS configuration**
```
backend:
  name: git-gateway
  branch: master
media_folder: static/img
public_folder: /img
collections:
  - name: blog
    label: Blog
    folder: content/blog
    format: frontmatter
    create: true
    slug: "{{slug}}"
    editor:
      preview: false
    fields:
      - label: Title
        name: title
        widget: string
      - label: Description
        name: description
        widget: string
      - label: Keywords
        name: keywords
        widget: string
      - label: Author
        name: author
        widget: string
      - label: Publish Date
        name: createdAt
        widget: datetime
      - label: Cover Image
        name: coverImg
        widget: image
      - label: Cover Image Alt Text
        name: coverImgAlt
        widget: string
      - label: Featured
        name: featured
        widget: boolean
      - label: Published
        name: published
        widget: boolean
      - label: Body
        name: body
        widget: markdown
    publish: true
    type: folder_based_collection
    sortable_fields:
      - commit_date
      - title
      - author
      - description
    view_filters: []
    view_groups: []
publish_mode: simple
slug:
  encoding: unicode
  clean_accents: false
  sanitize_replacement: "-"
isFetching: false
error: null

```

**Additional context**

**Comment by martinjagodic** [comment]
Hi @ankitsinghaniyaz, we believe that you have a problem, but in order for anybody to help you, you need to provide as much detail as possible. The issue template contains the bare minimum of what is required (how to reproduce, expected behaviour, screenshots, etc..).

I'm closing this issue for now. If the problem persists, please open a new issue with all of the details filled out. Also, before posting a new issue, please verify that everything is all right with your environment (computer, internet, browser) and verify whether this issue was already reported by someone else. For general help, please turn to our [Slack](https://decapcms.org/chat).
