### ISSUE TITLE
TypeError: t is undefined

### ISSUE THREAD

**Issue by loutre2** [netlify/netlify-cms#6601]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Applicable Versions:**
 - Netlify CMS version: `netlify-cms@2.10.192`
 - Git provider: `git-gateway`
 - Browser version: `Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:107.0) Gecko/20100101 Firefox/107.0`

**CMS configuration**
```
backend:
  name: git-gateway
  branch: master
  repo: waharnum/eva-hd.com
media_folder: netlify/src/img/uploads
collections:
  - name: pages
    label: Page
    folder: netlify/src/pages
    create: true
    fields:
      - label: Title
        name: title
        widget: string
      - label: Body
        name: body
        widget: markdown
    publish: true
    type: folder_based_collection
    sortable_fields:
      - commit_date
      - title
      - commit_author
    view_filters: []
    view_groups: []
publish_mode: simple
slug:
  encoding: unicode
  clean_accents: false
  sanitize_replacement: "-"
public_folder: /netlify/src/img/uploads
isFetching: false
error: null

```

**Additional context**

**Comment by martinjagodic** [comment]
Hi @loutre2, we believe that you have a problem, but in order for anybody to help you, you need to provide as much detail as possible. The issue template contains the bare minimum of what is required (how to reproduce, expected behaviour, screenshots, etc..).

I'm closing this issue for now. If the problem persists, please open a new issue with all of the details filled out. Also, before posting a new issue, please verify that everything is all right with your environment (computer, internet, browser) and verify whether this issue was already reported by someone else. For general help, please turn to our [Slack](https://decapcms.org/chat).
