### ISSUE TITLE
Bullet list entry starting with a shortcode  is deleted when moving between Rich Text and Markdown

### ISSUE THREAD

**Issue by yuri-g-taboola** [netlify/netlify-cms#6634]
**Describe the bug**

When changing from markdown to rich text the bullet list item is being removed if it starts with shortcode , e.g : 
`* <ShortCode/>`

**To Reproduce**

1. start the development environment 
`yarn develop`
2.  Go to posts admin page 
http://localhost:8080/#/collections/posts
3. Click on `New Post`
4. Scroll to the `Body` element
5. Verify the Markdown mode is toggled on
6. Type the following sequence
`*` <kbd>Backspace</kbd> <kbd>Space</kbd> `<ShortCode/>`
Note: The <kbd>Backspace</kbd> is needed only to remove the automatically added `ZWNBSP`.  If there is no `ZWNBSP` added automatically you don't need the <kbd>Backspace</kbd>
7. Toggle `Rich Text` mode
8. The list item disappears  

**Expected behavior**

The list item should remain in place

**Screenshots**

**Applicable Versions:**

 - Netlify CMS version: latest
 - Git provider: Github
 - OS: macOS Monterey 12.6.1
 - Browser version chrome 107.0.5304.110

 - Node.JS version:

**CMS configuration**

**Additional context**

**Comment by martinjagodic** [comment]
Hi @yuri-g-taboola, we believe that you have a problem, but in order for anybody to help you, you need to provide as much detail as possible. The issue template contains the bare minimum of what is required (how to reproduce, expected behaviour, screenshots, etc..).

I'm closing this issue for now. If the problem persists, please open a new issue with all of the details filled out. Also, before posting a new issue, please verify that everything is all right with your environment (computer, internet, browser) and verify whether this issue was already reported by someone else. For general help, please turn to our [Slack](https://decapcms.org/chat).
