### ISSUE TITLE
break tag is not working properly

### ISSUE THREAD

**Issue by MDSanketh006** [netlify/netlify-cms#6672]
we are using a cms and when we use break tag i.e <br></br> it breaks the line, but when we add any data or string between it it is breaking the code and giving some error. 

<br></br> : works fine.
<br>some line...</br> : breaks the code.

this was working fine in the "next-mdx-remote": "^3.0.4"
but with latest version it is giving error. 

please some give solution. the code is in production and rising error now

**Comment by martinjagodic** [comment]
Hi @MDSanketh006, we believe that you have a problem, but in order for anybody to help you, you need to provide as much detail as possible. The issue template contains the bare minimum of what is required (how to reproduce, expected behaviour, screenshots, etc..).

I'm closing this issue for now. If the problem persists, please open a new issue with all of the details filled out. Also, before posting a new issue, please verify that everything is all right with your environment (computer, internet, browser) and verify whether this issue was already reported by someone else. For general help, please turn to our [Slack](https://decapcms.org/chat).
