### ISSUE TITLE
Add `label_plural` field to collection config

### ISSUE THREAD

**Issue by verythorough** [netlify/netlify-cms#684]
**- Do you want to request a *feature* or report a *bug*?**
feature

**- What is the current behavior?**
The `label` field for a given collection is displayed in all places in the UI where the collection is referenced. At the moment, this is not pluralized in any way, so a collection with label "Post" will display as simply, "Post" in the sidebar. If you change the label to "Posts," it looks good in the sidebar, but "New Posts" doesn't make sense.

We used to have programmatic pluralization, but it sometimes produced undesirable results, and was [removed](https://github.com/netlify/netlify-cms/pull/503).

**- What is the desired behavior?**
It would be nice to have an optional `label_plural` field (or something similar), allowing implementers to specify a label version to use in cases where the UI calls for a plural. With this in place, we can bring back programmatic pluralization and use it as a default when the manual plural isn't specified.

**Comment by erquhart** [comment]
Along with this I'd like to reintroduce automatic pluralization as a fallback, it'll work for a lot of use cases.

**Comment by verythorough** [comment]
(which I did actually mention) ;)

**Comment by erquhart** [comment]
Yikes you totally did 🤦‍♂️

**Comment by DirtyF** [comment]
- [ ] use single instead of plural for Collections on buttons (posts) 

![quick add](https://user-images.githubusercontent.com/103008/33794626-9cbf22fa-dccf-11e7-8e6d-526b09529a3d.png)
![new post](https://user-images.githubusercontent.com/103008/33794627-9ced0224-dccf-11e7-9a15-4c58796cf7b4.png)
![collections-newl](https://user-images.githubusercontent.com/103008/33794628-9d1c687a-dccf-11e7-8c57-9b2ab726a3df.png)

**Comment by peduarte** [comment]
Hello 👋  I'm happy to pick this issue up and raise a PR for it.

**Comment by erquhart** [comment]
Thanks @peduarte!
