### ISSUE TITLE
Can't un-blockquote a quote in editor

### ISSUE THREAD

**Issue by bert-bruggeman** [netlify/netlify-cms#761]
**- Do you want to request a *feature* or report a *bug*?**
Bug
**- What is the current behavior?**
Selecting an existing blockquote in the editor doesn't highlight the blockquote icon, after clicking on the icon the editor creates a blockquote in the existing blockquote...

**- What is the expected behavior?**
 the blockquote icon should be highlighted when an existing quote is selected, the blockquote should be un-quoted after clicking it..
**- Please mention your CMS, node.js, and operating system version.**
Cms 0.6, chrome on fedora linux 23

**Comment by bert-bruggeman** [comment]
The issue only appears on existing entries...

**Comment by erquhart** [comment]
Ah, yep, got it.

**Comment by cwahlfeldt** [comment]
I'm working on this!

**Comment by cwahlfeldt** [comment]
It seems that the HTML is changed when viewing a Markdown widget in a post that already has a blockquote. When you make a blockquote using the editor the original html that it produces is:

```
<blockquote>
  <span>text</span>
</blockquote>
```

Upon revisiting the post edit page from the dashboard, the html changes to a blockquote with a paragraph as its child instead of a span and thus thinks its a paragraph not a quote.

```
<blockquote>
  <p>text</p>
</blockquote>
```

Not sure how it "re-hydrates" data when its viewed again? Also note that this isn't retrieving from a file, I believe its retrieving the data from localstorage or some other storage (localforeage?). Still learning a ton about the ENV so bear with me. Cheers!

**Comment by erquhart** [comment]
@cwahlfeldt so glad you're digging into this!

The storage is actually whatever backend Netlify CMS is using (which currently can only be GitHub for live projects), it loads the entry fresh each time it's opened.

From a high level:

1. the markdown widget is a [Slate](slatejs.org) editor
2. we use [Remark](remarkjs.org) as our Markdown AST
3. when a change occurs in the editor, Slate stores it (in it's own Slate AST)
4. we manually create our own Remark AST from that - e.g., quote node is parsed [here](https://github.com/netlify/netlify-cms/blob/master/src/components/EditorWidgets/Markdown/serializers/slateRemark.js#L376)
5. the Remark AST is the source of truth for the widget and the preview
6. the preview is updated by a Remark module that converts the Remark AST to HTML
5. when we save and persist the entry, the Remark AST is serialized to a Markdown string
6. on entry load, the Markdown is converted to Remark AST by Remark (not manually as before)

I'm betting there's a difference between the Remark AST quote node that we create ourselves and the node that Remark creates when parsing from the Markdown string on load.

**Comment by bytrangle** [comment]
This issue was a long time ago, but can @bert-bruggeman or anyone with write access please revise the issue title?
At present, we can un-blockquote a quote in the editor. The only problem is that when an existing blockquote loses focus, and then got focussed again (either by clicking or selecting it), the blockquote toolbar icon is not highlighted.

![blockquote-toolbar-button](https://user-images.githubusercontent.com/28924121/116514006-9a59e000-a8f4-11eb-99bb-45c79588b436.gif)

**Comment by bytrangle** [comment]
@erquhart: This issue was opened three years ago and a lot of things have changed in the Netlify CMS. There was two parts in the original issue:
- Select an existing quoteblock in the editor, then click the quoteblock toolbar icon should un-blockquote it. 
- Selecting an existing quoteblock doesn't highlight the quoteblock icon in the toolbar.

Currently, the first part seems to have been solved. I can select a quoteblock, then click the quoteblock button to toggle it on and off.

However, the second parts still remains. Indeed, I've discovered another issue.

All the text styles offered by the editor can be divided into three groups:
- block element (Headings from H1 to H6, quoteblock, bulleted list, numbered list).
- mark element (bold, italic, code)
- inline element (hyperlink)

Selecting either quoteblock, numbered list and bulleted list doesn't highlight the relevant icon in the toolbar. However, selecting the heading works fine.

Please see the demo below.

![block-style-button-doesnt-highlight](https://user-images.githubusercontent.com/28924121/116839679-6edd3b00-abfd-11eb-8981-2278165a2789.gif)

Should I create a separate issue for this?

**Comment by erezrokah** [comment]
> Should I create a separate issue for this?

Hi @bytrangle, that's a good idea. I'll close this one. Can you please open a new one with a reproduction and link to this one?
