### ISSUE TITLE
Decide on error boundaries.

### ISSUE THREAD

**Issue by tech4him1** [netlify/netlify-cms#771]
Now that we are on React 16, we should probably decide where to create "error boundaries" (https://reactjs.org/blog/2017/07/26/error-handling-in-react-16.html). Right now, thrown errors will now dismount the entire app if not caught. Should they be per-widget? per-page? per-component?

**Comment by erquhart** [comment]
Agreed, thanks for raising this.

A prescriptive approach is probably best. Error boundaries can actually be dangerous otherwise - allowing parts of the app to run while other parts are inactive can lead to cases we simply don't expect and aren't set up for.

The first applied error boundary, and a generic, reusable boundary component, are in #779.

**Comment by tech4him1** [comment]
What about creating an error boundary around the entire app, so we don't just get a blank white screen on crash?

**Comment by erquhart** [comment]
With the generic component and the app now wrapped in it, I think we can close this.
