### ISSUE TITLE
Duplicate an existing entry

### ISSUE THREAD

**Issue by mtully** [netlify/netlify-cms#981]
**Feature request**

User story: When I am an editor creating new content in the CMS, I want to be able to duplicate an existing document, So I can reduce the number of redundant fields to fill out when creating new documents with similar information.

**Comment by erquhart** [comment]
You are the umpteenth person to mention this - let's discuss.

**Comment by mtully** [comment]
There are 2 places in the ui that make sense to me given the current toolbar/chrome. 

1. The top bar gives duplication equal weight as delete and is always available
2. Under the the Publish button, is helpful if you are migrating lots of content and are "in the flow."™️

<img width="1014" alt="screenshot 2018-01-11 11 52 05" src="https://user-images.githubusercontent.com/129630/34836873-2346a828-f6c7-11e7-8796-122c2fd1f935.png">

Regarding naming, the cms could create a hash every time a new file is created as the path. It would still be available to edit. This would force uniqueness validation on save, but would prevent any smart naming convention collisions or overwrites. This isn't perfect, for instance some collections aren't pages, so it could be just a hash and in the absence of a path, it is the path. Thoughts?

**Comment by raf-vs** [comment]
Adding to @mtully his comment on where to place the functionality:
A simple "copy" icon to the right of the title of an entry in a collection overview would be a good location imho.
Gives the user easy access to the copy feature without having to open an existing entry first before copying it.

![schermafbeelding 2018-01-15 om 11 13 27](https://user-images.githubusercontent.com/868224/34938240-db4ce3ce-f9e7-11e7-90e6-25c177f46dfd.png)

Clicking the "copy"-icon would bring the user to the edit screen for the new entry with the fields pre-filled with the content from the source entry.

Maybe simply adding "- copy time/date stamp" would be a solution for the naming issue?
It would be up to the user to change the title of the item upon editing and before saving/publishing

**Comment by erquhart** [comment]
This is good stuff - @neutyp, @ziburski, other designers, any thoughts?

One thing that comes to mind is that Netlify CMS is about to start supporting a lot of things in the interface - it's relatively bare compared to what it's going to be not too far down the road. A single item in the collection view might have a number of different actions, statuses and labels associated with it, so that a single control wouldn't be able to take up quite so much space as depicted above.

How can we minimize the real estate this takes up without harming convenience to editors that need it?

**Comment by neutyp** [comment]
I/we didn't even wan't delete in the editor experience, so that's not the right place for duplicate either. We're creeping back to the "button city" problem we had in that toolbar. These actions, including delete, should only take place at the top level, not within the editor

**Comment by ziburski** [comment]
> A single item in the collection view might have a number of different actions, statuses and labels associated with it

The most straightforward solution seems to be a simple dropdown with three dots then. It’s a known pattern and can be used throughout the CMS for actions like these. In fact, I proposed using it in the media library UI earlier: https://github.com/netlify/netlify-cms/issues/490#issuecomment-329564080

Here is what it could look like for the collection view:

![collection1](https://user-images.githubusercontent.com/1299080/35193232-ff2c13e8-fe9f-11e7-8863-3dfab744e0b0.jpg)
![collection2](https://user-images.githubusercontent.com/1299080/35193231-ff12e058-fe9f-11e7-9b33-94729da482b3.jpg)

> These actions, including delete, should only take place at the top level, not within the editor

Hmm. I think there are cases where you want to confirm the contents before duplicating or deleting. In that case, you would open the editor to check and then want to delete from there. Going back to the list and finding the post again do delete / duplicate from there would be cumbersome.

Though we can avoid the “button city” problem if we use the same dropdown in the editor:

![editor1](https://user-images.githubusercontent.com/1299080/35193350-67474208-fea1-11e7-9e11-a020b2afdf31.jpg)
![editor2](https://user-images.githubusercontent.com/1299080/35193351-67639bb0-fea1-11e7-805a-0614a6c50b97.jpg)
(Maybe reorder the top navigation then so that the dropdown doesn’t clash with the publish button.)

As for naming, wouldn’t appending a counter be enough? So “[Name]”, “[Name] 2”, “[Name] 3”.

**Comment by erquhart** [comment]
Thanks for the visuals @ziburski, that helps a lot. This is a great way to get multiple functions into play on both screens and I _love_ the look. We may need to iterate a bit on little stuff like the editor toolbar button appearance, but that's about it imo.

**Comment by mtully** [comment]
@ziburski -- these look great, definitely see the benefit of collecting file actions under an action menu. It keeps the UI clean and tucks the ominous "Delete" action away from the view.

@erquhart -- mind sharing some of the upcoming additions to the UI or point to any open PRs? Knowing where things are heading should help consider other locations for these actions.

**Comment by erquhart** [comment]
There really isn't much for new UI additions in the issues and PR's, mostly because we just completed an exhaustive overhaul of the entire UI and added a lot of things along the way for the 1.0 release that came out in December. Current focus is establishing extensibility - making it much easier to create widgets, customize the preview pane and editor in general, and other things along those lines.

That said, this project is community driven, so if you really want to see an improvement and folks are on board, you can make it happen and the community will support it along the way.

**Comment by mtully** [comment]
Bumping this up to the top. Going to take a crack at the duplication feature. I'm going to follow @ziburski design docs while accounting for the most recent interface items.

@erquhart do you see any potential conflicts or collisions in the editor or index views?

**Comment by erquhart** [comment]
@mtully nope, @ziburski's design handles my concern, have at it :)

**Comment by eLRuLL** [comment]
is the idea of this feature to only allow duplicates of "complete documents" or also for specific sections?

**Comment by erquhart** [comment]
This would cover complete documents, I'd recommend opening a separate issue for sections with a bit more info about the problem you're looking to solve with that feature.

**Comment by mittalyashu** [comment]
@erquhart I think we can expand this topic from just duplication the post to Move/Copy/Duplicate/Delete the post _(according to issue: #981 and #1575)_.

Regarding the design this can be implemented.

![image](https://user-images.githubusercontent.com/29014463/44616783-f16da400-a873-11e8-8eae-9446162bd645.png)

![image](https://user-images.githubusercontent.com/29014463/44616785-f6325800-a873-11e8-8db5-d1b68a125f4e.png)

**Comment by mtully** [comment]
@mittalyashu -- these are really useful features!
@erquhart  -- I haven't taken any steps forward on working on this issue, can you please remove the claimed tag? Also, how does this community feel about bounties?

**Comment by erquhart** [comment]
@mtully haven't encountered any yet, what do you have in mind?

**Comment by wiadev** [comment]
@mtully I can't see such an option to duplicate on my cms.

**Comment by tomrutgers** [comment]
@wiadev the images above are conceptual designs, not live screenshots from the cms. This feature hasn't been implemented, that's why this feature request is stil open.

**Comment by wiadev** [comment]
I see. looking forward to it then. thanks.

**Comment by speexy** [comment]
I just opened the issue #2116, which is another approach to the copy-workflow.

**Comment by hacknug** [comment]
Please, be a good bot and don't close this. @erquhart promised us changes soon. Let him close it when it's time 🙂
